import antfu from '@antfu/eslint-config';
import unocss from '@unocss/eslint-config/flat';

// Globals generated by unplugin-auto-import at build time.
// If this file doesn't exist yet, run `pnpm build` once first.
let autoImportGlobals = {};
try {
  const mod = await import('./.eslintrc-auto-import.json', { with: { type: 'json' } });
  autoImportGlobals = mod.default.globals ?? {};
}
catch {
  // file not generated yet — first build will create it
}

export default antfu(
  {
    typescript: true,
    vue: true,
  },
  unocss,
  {
    languageOptions: {
      globals: autoImportGlobals,
    },
    rules: {
      'curly': ['error', 'all'],
      'style/semi': ['error', 'always'],
      '@typescript-eslint/no-use-before-define': ['error', { allowNamedExports: true, functions: false }],
      'vue/no-empty-component-block': ['error'],
      'no-restricted-imports': ['error', {
        paths: [{
          name: '@vueuse/core',
          importNames: ['useClipboard'],
          message: 'Please use local useCopy from src/composable/copy.ts instead of useClipboard.',
        }],
      }],
    },
  },
);
