export type FilmType = 'bw' | 'color-neg' | 'slide';

export interface FilmStock {
  id: string
  name: string
  manufacturer: string
  type: FilmType
  iso: number
  /** Schwarzschild exponent: t_adjusted = t_metered ^ exponent */
  exponent: number
  /** No reciprocity failure up to this many seconds (e.g. Acros = 120) */
  noFailureUpTo?: number
  /** Exhibits color shift on long exposures */
  colorShift: boolean
  /** 'manufacturer' = published data, 'community' = compiled from community sources */
  sourceReliability: 'manufacturer' | 'community'
  notes?: string
}

export const filmStocks: FilmStock[] = [
  // ─── Ilford B&W ─────────────────────────────────────────────────────────────
  {
    id: 'ilford-hp5',
    name: 'HP5 Plus',
    manufacturer: 'Ilford',
    type: 'bw',
    iso: 400,
    exponent: 1.31,
    colorShift: false,
    sourceReliability: 'manufacturer',
  },
  {
    id: 'ilford-fp4',
    name: 'FP4 Plus',
    manufacturer: 'Ilford',
    type: 'bw',
    iso: 125,
    exponent: 1.26,
    colorShift: false,
    sourceReliability: 'manufacturer',
  },
  {
    id: 'ilford-delta100',
    name: 'Delta 100',
    manufacturer: 'Ilford',
    type: 'bw',
    iso: 100,
    exponent: 1.26,
    colorShift: false,
    sourceReliability: 'manufacturer',
  },
  {
    id: 'ilford-delta400',
    name: 'Delta 400',
    manufacturer: 'Ilford',
    type: 'bw',
    iso: 400,
    exponent: 1.41,
    colorShift: false,
    sourceReliability: 'manufacturer',
  },
  {
    id: 'ilford-delta3200',
    name: 'Delta 3200',
    manufacturer: 'Ilford',
    type: 'bw',
    iso: 3200,
    exponent: 1.33,
    colorShift: false,
    sourceReliability: 'manufacturer',
  },
  {
    id: 'ilford-panf',
    name: 'Pan F Plus',
    manufacturer: 'Ilford',
    type: 'bw',
    iso: 50,
    exponent: 1.33,
    colorShift: false,
    sourceReliability: 'manufacturer',
  },
  {
    id: 'ilford-sfx',
    name: 'SFX 200',
    manufacturer: 'Ilford',
    type: 'bw',
    iso: 200,
    exponent: 1.31,
    colorShift: false,
    sourceReliability: 'manufacturer',
  },
  {
    id: 'ilford-ortho',
    name: 'Ortho Plus',
    manufacturer: 'Ilford',
    type: 'bw',
    iso: 80,
    exponent: 1.25,
    colorShift: false,
    sourceReliability: 'manufacturer',
  },
  {
    id: 'ilford-xp2',
    name: 'XP2 Super',
    manufacturer: 'Ilford',
    type: 'bw',
    iso: 400,
    exponent: 1.31,
    colorShift: false,
    sourceReliability: 'community',
    notes: 'C-41 chromogenic. Exponent approximated from community sources.',
  },

  // ─── Kodak B&W ──────────────────────────────────────────────────────────────
  {
    id: 'kodak-tmax100',
    name: 'T-Max 100',
    manufacturer: 'Kodak',
    type: 'bw',
    iso: 100,
    exponent: 1.25,
    colorShift: false,
    sourceReliability: 'community',
    notes: 'Excellent reciprocity. Minimal correction needed under 10s.',
  },
  {
    id: 'kodak-tmax400',
    name: 'T-Max 400',
    manufacturer: 'Kodak',
    type: 'bw',
    iso: 400,
    exponent: 1.30,
    colorShift: false,
    sourceReliability: 'community',
  },
  {
    id: 'kodak-trix',
    name: 'Tri-X 400',
    manufacturer: 'Kodak',
    type: 'bw',
    iso: 400,
    exponent: 1.33,
    colorShift: false,
    sourceReliability: 'community',
  },

  // ─── Fujifilm B&W ───────────────────────────────────────────────────────────
  {
    id: 'fuji-acros100ii',
    name: 'Neopan Acros 100 II',
    manufacturer: 'Fujifilm',
    type: 'bw',
    iso: 100,
    exponent: 1.30,
    noFailureUpTo: 120,
    colorShift: false,
    sourceReliability: 'manufacturer',
    notes: 'No correction needed up to 120s. A primary selling point of Acros.',
  },
  {
    id: 'fuji-acros100',
    name: 'Neopan Acros 100 (original)',
    manufacturer: 'Fujifilm',
    type: 'bw',
    iso: 100,
    exponent: 1.30,
    noFailureUpTo: 120,
    colorShift: false,
    sourceReliability: 'manufacturer',
    notes: 'No correction needed up to 120s.',
  },

  // ─── Foma B&W ───────────────────────────────────────────────────────────────
  {
    id: 'foma-100',
    name: 'Fomapan 100',
    manufacturer: 'Foma',
    type: 'bw',
    iso: 100,
    exponent: 1.35,
    colorShift: false,
    sourceReliability: 'community',
  },
  {
    id: 'foma-200',
    name: 'Fomapan 200',
    manufacturer: 'Foma',
    type: 'bw',
    iso: 200,
    exponent: 1.35,
    colorShift: false,
    sourceReliability: 'community',
  },
  {
    id: 'foma-400',
    name: 'Fomapan 400',
    manufacturer: 'Foma',
    type: 'bw',
    iso: 400,
    exponent: 1.38,
    colorShift: false,
    sourceReliability: 'community',
  },

  // ─── Kentmere B&W ───────────────────────────────────────────────────────────
  {
    id: 'kentmere-100',
    name: 'Kentmere 100',
    manufacturer: 'Kentmere',
    type: 'bw',
    iso: 100,
    exponent: 1.26,
    colorShift: false,
    sourceReliability: 'community',
    notes: 'Manufactured by Harman/Ilford. Similar reciprocity to Delta 100.',
  },
  {
    id: 'kentmere-400',
    name: 'Kentmere 400',
    manufacturer: 'Kentmere',
    type: 'bw',
    iso: 400,
    exponent: 1.29,
    colorShift: false,
    sourceReliability: 'community',
  },

  // ─── Rollei B&W ─────────────────────────────────────────────────────────────
  {
    id: 'rollei-rpx100',
    name: 'RPX 100',
    manufacturer: 'Rollei',
    type: 'bw',
    iso: 100,
    exponent: 1.29,
    colorShift: false,
    sourceReliability: 'community',
  },
  {
    id: 'rollei-rpx400',
    name: 'RPX 400',
    manufacturer: 'Rollei',
    type: 'bw',
    iso: 400,
    exponent: 1.31,
    colorShift: false,
    sourceReliability: 'community',
  },
  {
    id: 'rollei-ortho25',
    name: 'Ortho 25 Plus',
    manufacturer: 'Rollei',
    type: 'bw',
    iso: 25,
    exponent: 1.25,
    colorShift: false,
    sourceReliability: 'community',
  },

  // ─── Kodak Color Negative ────────────────────────────────────────────────────
  {
    id: 'kodak-portra160',
    name: 'Portra 160',
    manufacturer: 'Kodak',
    type: 'color-neg',
    iso: 160,
    exponent: 1.35,
    colorShift: true,
    sourceReliability: 'community',
  },
  {
    id: 'kodak-portra400',
    name: 'Portra 400',
    manufacturer: 'Kodak',
    type: 'color-neg',
    iso: 400,
    exponent: 1.35,
    colorShift: true,
    sourceReliability: 'community',
  },
  {
    id: 'kodak-portra800',
    name: 'Portra 800',
    manufacturer: 'Kodak',
    type: 'color-neg',
    iso: 800,
    exponent: 1.40,
    colorShift: true,
    sourceReliability: 'community',
  },
  {
    id: 'kodak-ektar100',
    name: 'Ektar 100',
    manufacturer: 'Kodak',
    type: 'color-neg',
    iso: 100,
    exponent: 1.35,
    colorShift: true,
    sourceReliability: 'community',
  },
  {
    id: 'kodak-gold200',
    name: 'Gold 200',
    manufacturer: 'Kodak',
    type: 'color-neg',
    iso: 200,
    exponent: 1.40,
    colorShift: true,
    sourceReliability: 'community',
  },
  {
    id: 'kodak-ultramax400',
    name: 'UltraMax 400',
    manufacturer: 'Kodak',
    type: 'color-neg',
    iso: 400,
    exponent: 1.40,
    colorShift: true,
    sourceReliability: 'community',
  },
  {
    id: 'kodak-colorplus200',
    name: 'ColorPlus 200',
    manufacturer: 'Kodak',
    type: 'color-neg',
    iso: 200,
    exponent: 1.40,
    colorShift: true,
    sourceReliability: 'community',
  },

  // ─── Fujifilm Color Negative ─────────────────────────────────────────────────
  {
    id: 'fuji-pro400h',
    name: 'Pro 400H',
    manufacturer: 'Fujifilm',
    type: 'color-neg',
    iso: 400,
    exponent: 1.30,
    colorShift: true,
    sourceReliability: 'community',
    notes: 'Discontinued 2021.',
  },
  {
    id: 'fuji-fujicolor200',
    name: 'Fujicolor 200',
    manufacturer: 'Fujifilm',
    type: 'color-neg',
    iso: 200,
    exponent: 1.40,
    colorShift: true,
    sourceReliability: 'community',
  },
  {
    id: 'fuji-c200',
    name: 'Fujicolor C200',
    manufacturer: 'Fujifilm',
    type: 'color-neg',
    iso: 200,
    exponent: 1.40,
    colorShift: true,
    sourceReliability: 'community',
  },
  {
    id: 'fuji-superia400',
    name: 'Superia X-TRA 400',
    manufacturer: 'Fujifilm',
    type: 'color-neg',
    iso: 400,
    exponent: 1.38,
    colorShift: true,
    sourceReliability: 'community',
  },

  // ─── Cinestill ──────────────────────────────────────────────────────────────
  {
    id: 'cinestill-800t',
    name: '800T',
    manufacturer: 'Cinestill',
    type: 'color-neg',
    iso: 800,
    exponent: 1.40,
    colorShift: true,
    sourceReliability: 'community',
    notes: 'Based on Kodak Vision3 500T.',
  },
  {
    id: 'cinestill-400d',
    name: '400D',
    manufacturer: 'Cinestill',
    type: 'color-neg',
    iso: 400,
    exponent: 1.38,
    colorShift: true,
    sourceReliability: 'community',
  },
  {
    id: 'cinestill-50d',
    name: '50D',
    manufacturer: 'Cinestill',
    type: 'color-neg',
    iso: 50,
    exponent: 1.35,
    colorShift: true,
    sourceReliability: 'community',
  },

  // ─── Fujifilm Slide / E6 ─────────────────────────────────────────────────────
  {
    id: 'fuji-velvia50',
    name: 'Velvia 50',
    manufacturer: 'Fujifilm',
    type: 'slide',
    iso: 50,
    exponent: 1.30,
    colorShift: true,
    sourceReliability: 'community',
    notes: 'Significant warm color shift on long exposures. Consider CC cyan filtration.',
  },
  {
    id: 'fuji-velvia100',
    name: 'Velvia 100',
    manufacturer: 'Fujifilm',
    type: 'slide',
    iso: 100,
    exponent: 1.28,
    colorShift: true,
    sourceReliability: 'community',
  },
  {
    id: 'fuji-provia100f',
    name: 'Provia 100F',
    manufacturer: 'Fujifilm',
    type: 'slide',
    iso: 100,
    exponent: 1.30,
    colorShift: true,
    sourceReliability: 'community',
  },
  {
    id: 'fuji-provia400x',
    name: 'Provia 400X',
    manufacturer: 'Fujifilm',
    type: 'slide',
    iso: 400,
    exponent: 1.30,
    colorShift: true,
    sourceReliability: 'community',
    notes: 'Discontinued.',
  },

  // ─── Kodak Slide / E6 ────────────────────────────────────────────────────────
  {
    id: 'kodak-ektachrome-e100',
    name: 'Ektachrome E100',
    manufacturer: 'Kodak',
    type: 'slide',
    iso: 100,
    exponent: 1.30,
    colorShift: true,
    sourceReliability: 'community',
  },
];
