export const ndrCategories: {
  category: string
  codes: {
    code: string
    name: string
    description: string
    cause: string
    fix: string
    severity: 'Info' | 'Warning' | 'Error' | 'Critical'
  }[]
}[] = [
  {
    category: 'Authentication & Authorization (5.7.x)',
    codes: [
      {
        code: '5.7.1',
        name: 'Delivery Not Authorized',
        description: 'The sending address is not permitted to send to this recipient.',
        cause: 'The recipient has restrictions on who can send to them, or the sender is blocked by a transport rule.',
        fix: 'Check recipient delivery restrictions in Exchange Admin Center. Check transport rules for blocks on the sender domain or address.',
        severity: 'Error',
      },
      {
        code: '5.7.23',
        name: 'SPF Validation Failed',
        description: 'The message was rejected because the sending domain SPF record does not include the sending server.',
        cause: 'The sending IP is not listed in the domain SPF record, or SPF is misconfigured.',
        fix: 'Verify the sending server IP is included in the SPF record. Check for SPF flattening issues or too many DNS lookups (max 10).',
        severity: 'Error',
      },
      {
        code: '5.7.25',
        name: 'SPF Permanent Error',
        description: 'A permanent SPF error occurred during validation.',
        cause: 'SPF record has a syntax error, exceeds DNS lookup limit, or returns a PermError.',
        fix: 'Validate SPF record syntax using an SPF checker. Reduce DNS lookups to under 10.',
        severity: 'Error',
      },
      {
        code: '5.7.26',
        name: 'SPF Validation Failed (Forwarded)',
        description: 'Message failed SPF because it was forwarded and the forwarding server is not in the SPF record.',
        cause: 'Email forwarding breaks SPF alignment. The forwarder IP is not in the original sender SPF record.',
        fix: 'Implement DMARC with DKIM signing so forwarded messages pass DKIM even when SPF fails. Use SRS (Sender Rewriting Scheme) on the forwarding server.',
        severity: 'Warning',
      },
      {
        code: '5.7.57',
        name: 'Client Not Authenticated',
        description: 'The SMTP client was not authenticated and is not permitted to relay.',
        cause: 'Application or device attempting to relay without proper authentication.',
        fix: 'Configure SMTP AUTH on the sending application. Use a connector or dedicated relay with proper credentials.',
        severity: 'Error',
      },
      {
        code: '5.7.60',
        name: 'SMTP Client Does Not Have Permission',
        description: 'The client does not have permission to submit mail to this server.',
        cause: 'The connector or receive connector is not configured to accept connections from this IP.',
        fix: 'Add the sending IP to the appropriate receive connector in Exchange Admin Center.',
        severity: 'Error',
      },
      {
        code: '5.7.64',
        name: 'TenantAttribution - Tenant Relay Blocked',
        description: 'Your organization has blocked outbound relay from this source.',
        cause: 'Connector configuration issue or tenant policy blocking relay.',
        fix: 'Review outbound connectors in Exchange Admin Center. Check tenant relay settings.',
        severity: 'Error',
      },
      {
        code: '5.7.67',
        name: 'Sender Not Authenticated (Inbound Connector)',
        description: 'The inbound connector requires authentication but the sender did not authenticate.',
        cause: 'Inbound connector is configured to require certificate or IP-based authentication.',
        fix: 'Check inbound connector configuration. Ensure the sending server meets the authentication requirements.',
        severity: 'Error',
      },
      {
        code: '5.7.133',
        name: 'Sender Not in Group',
        description: 'The sender is not a member of the distribution group required to send to this recipient.',
        cause: 'The recipient is a group with membership-restricted sending.',
        fix: 'Add the sender to the allowed senders list on the distribution group, or adjust group delivery restrictions.',
        severity: 'Warning',
      },
      {
        code: '5.7.134',
        name: 'Sender Not Permitted for Mailbox',
        description: 'The sender is not permitted to send to this mailbox.',
        cause: 'Mailbox has specific sender restrictions configured.',
        fix: 'Check the mailbox delivery restrictions in Exchange Admin Center under mailbox > mail flow settings.',
        severity: 'Warning',
      },
      {
        code: '5.7.135',
        name: 'Sender Not in Safe Senders',
        description: 'The recipient only accepts mail from their safe senders list.',
        cause: 'The mailbox is configured to only accept from contacts or safe senders.',
        fix: 'Have the recipient add the sender to their safe senders list, or adjust mailbox policy.',
        severity: 'Warning',
      },
      {
        code: '5.7.136',
        name: 'Sender Not Permitted (User Policy)',
        description: 'Mail rejected per sender policy for this user.',
        cause: 'User-level policy is blocking the sender.',
        fix: 'Review user-level mail flow rules and safe sender configurations.',
        severity: 'Warning',
      },
      {
        code: '5.7.501',
        name: 'Access Denied - Spam Policy',
        description: 'The sending IP or domain is blocked due to spam policy.',
        cause: 'IP reputation or spam score triggered a block.',
        fix: 'Check IP reputation at MXToolbox or Microsoft SNDS. Submit delisting request if IP is legitimate.',
        severity: 'Error',
      },
      {
        code: '5.7.503',
        name: 'Access Denied - Banned Sender',
        description: 'The sending account or domain has been banned.',
        cause: 'The sender has been explicitly blocked by Microsoft or the recipient tenant.',
        fix: 'Use Microsoft Sender Support portal to request a review.',
        severity: 'Critical',
      },
      {
        code: '5.7.505',
        name: 'Access Denied - Sending Account Suspended',
        description: 'The sending account has been suspended for sending spam.',
        cause: 'Account was compromised and used to send spam, triggering an outbound spam block.',
        fix: 'Investigate the account for compromise. Reset credentials, enable MFA, review sent items. Unblock via Security & Compliance Center > Review restricted users.',
        severity: 'Critical',
      },
      {
        code: '5.7.506',
        name: 'Bad HELO',
        description: 'The server rejected the connection because of a bad HELO/EHLO greeting.',
        cause: 'The sending server is using a hostname in HELO/EHLO that does not match its PTR record or is a private IP.',
        fix: 'Ensure the sending server uses its public FQDN in HELO/EHLO. Verify PTR record matches the FQDN.',
        severity: 'Error',
      },
      {
        code: '5.7.508',
        name: 'Access Denied - IP Sending Too Fast',
        description: 'The sending IP is throttled for sending too many messages.',
        cause: 'The IP is sending volume above the allowed threshold.',
        fix: 'Reduce sending rate. If legitimate bulk mail, use a dedicated IP with a warm-up period.',
        severity: 'Warning',
      },
      {
        code: '5.7.509',
        name: 'DMARC Policy Violation - Reject',
        description: 'Message rejected due to DMARC policy.',
        cause: 'The message failed DMARC alignment and the policy is p=reject.',
        fix: 'Verify SPF includes the sending IP and DKIM is signing with the correct domain.',
        severity: 'Error',
      },
      {
        code: '5.7.510',
        name: 'Access Denied - Message Does Not Meet IPv6 Requirements',
        description: 'Messages sent via IPv6 must pass reverse DNS lookup.',
        cause: 'The sending IPv6 address does not have a valid PTR record.',
        fix: 'Configure a PTR record for the sending IPv6 address, or send via IPv4.',
        severity: 'Error',
      },
      {
        code: '5.7.511',
        name: 'Access Denied - Banned Sender',
        description: 'This sender is banned from sending mail.',
        cause: 'The sender has been explicitly blocked.',
        fix: 'Review blocked senders list in anti-spam policies.',
        severity: 'Error',
      },
      {
        code: '5.7.512',
        name: 'Access Denied - Message Must Be RFC 5321 Compliant',
        description: 'The message does not comply with RFC 5321 requirements.',
        cause: 'Missing or malformed required SMTP headers.',
        fix: 'Ensure the sending application generates RFC-compliant messages with valid From, To, and Date headers.',
        severity: 'Error',
      },
      {
        code: '5.7.606',
        name: 'Access Denied - Banned Sending IP',
        description: 'The sending IP is on Microsoft block list.',
        cause: 'The IP has been flagged for sending spam or malicious content.',
        fix: 'Submit a delisting request at https://sender.office.com. Investigate why the IP was flagged.',
        severity: 'Critical',
      },
      {
        code: '5.7.700',
        name: 'Access Denied - Tenant Policy',
        description: 'Message rejected due to a tenant-level policy.',
        cause: 'A tenant-wide transport rule or policy is blocking the message.',
        fix: 'Review transport rules in Exchange Admin Center > Mail Flow > Rules.',
        severity: 'Error',
      },
      {
        code: '5.7.708',
        name: 'Access Denied - Tenant Blocked',
        description: 'Service not available. Access denied. Tenant is blocked.',
        cause: 'The sending tenant has been blocked by Microsoft, often due to compromised accounts sending spam.',
        fix: 'Contact Microsoft Support. Review outbound spam reports and compromised accounts.',
        severity: 'Critical',
      },
      {
        code: '5.7.750',
        name: 'Client Blocked - Too Many Spam Complaints',
        description: 'The sending domain or IP is blocked due to excessive spam complaints.',
        cause: 'Recipients have marked too many messages as spam.',
        fix: 'Review mailing list hygiene. Implement unsubscribe mechanisms. Check spam complaint rate.',
        severity: 'Critical',
      },
      {
        code: '5.7.900',
        name: 'Message Blocked - Safe Attachments',
        description: 'Microsoft Defender Safe Attachments blocked the message.',
        cause: 'An attachment was determined to be malicious by Safe Attachments detonation.',
        fix: 'The attachment contains malware. Do not send. If false positive, review Safe Attachments policy and submit to Microsoft.',
        severity: 'Critical',
      },
      {
        code: '5.7.901',
        name: 'Message Blocked - Safe Links',
        description: 'Microsoft Defender Safe Links blocked the message.',
        cause: 'A URL in the message was flagged as malicious.',
        fix: 'Review the URLs in the message. If false positive, submit to Microsoft via the Submissions portal.',
        severity: 'Critical',
      },
    ],
  },
  {
    category: 'DKIM Errors (5.7.2xx)',
    codes: [
      {
        code: '5.7.200',
        name: 'DKIM Signature Missing',
        description: 'The message does not have a DKIM signature and the policy requires one.',
        cause: 'Sending domain has a DKIM policy requiring signatures but the message was not signed.',
        fix: 'Enable DKIM signing for the sending domain in Exchange Admin Center or DNS.',
        severity: 'Error',
      },
      {
        code: '5.7.201',
        name: 'DKIM Signature Verification Failed',
        description: 'The DKIM signature on the message could not be verified.',
        cause: 'DKIM public key in DNS does not match the private key used to sign, or the message was modified in transit.',
        fix: 'Verify DKIM selector DNS records are correct. Re-rotate DKIM keys if necessary.',
        severity: 'Error',
      },
      {
        code: '5.7.202',
        name: 'DKIM Key Revoked',
        description: 'The DKIM key used to sign the message has been revoked.',
        cause: 'The DKIM public key has been removed from DNS or set to p= (empty).',
        fix: 'Publish a new DKIM key pair and update the DNS TXT record.',
        severity: 'Error',
      },
      {
        code: '5.7.203',
        name: 'DKIM Key Not Found',
        description: 'The DKIM selector referenced in the signature was not found in DNS.',
        cause: 'The selector DNS record is missing or the selector in the signature is incorrect.',
        fix: 'Verify the DKIM selector TXT record exists in DNS for the signing domain.',
        severity: 'Error',
      },
    ],
  },
  {
    category: 'Recipient Issues (5.1.x)',
    codes: [
      {
        code: '5.1.0',
        name: 'Sender Denied',
        description: 'The sender address was rejected by the remote server.',
        cause: 'Sending address does not exist, is malformed, or is on a block list.',
        fix: 'Verify the sender address exists and is valid. Check outbound spam filter for blocked senders.',
        severity: 'Error',
      },
      {
        code: '5.1.1',
        name: 'Bad Destination Mailbox Address',
        description: 'The recipient email address does not exist.',
        cause: 'The address was mistyped, the mailbox was deleted, or the user never existed.',
        fix: 'Verify the recipient address is correct. Check if the mailbox was recently deleted or renamed.',
        severity: 'Error',
      },
      {
        code: '5.1.2',
        name: 'Invalid X.400 Address',
        description: 'The recipient has a non-SMTP address that could not be resolved.',
        cause: 'Legacy X.400 address format issue.',
        fix: 'Update the recipient address to use standard SMTP format.',
        severity: 'Error',
      },
      {
        code: '5.1.3',
        name: 'Invalid Recipient Address',
        description: 'The recipient address is syntactically invalid.',
        cause: 'Malformed email address in the To, CC, or BCC field.',
        fix: 'Check the recipient address for typos or invalid characters.',
        severity: 'Error',
      },
      {
        code: '5.1.4',
        name: 'Destination Mailbox Address Ambiguous',
        description: 'Multiple recipients match the address.',
        cause: 'Duplicate email address or proxy address conflict in Active Directory.',
        fix: 'Check for duplicate proxy addresses in Exchange or Azure AD.',
        severity: 'Error',
      },
      {
        code: '5.1.6',
        name: 'Destination Mailbox Address Invalid',
        description: 'The destination mailbox address is invalid.',
        cause: 'The address exists in AD but the mailbox is not properly configured.',
        fix: 'Verify the mailbox is properly provisioned in Exchange.',
        severity: 'Error',
      },
      {
        code: '5.1.7',
        name: 'Invalid Address',
        description: 'The sender or recipient address is malformed.',
        cause: 'Invalid characters or format in the email address.',
        fix: 'Check the address format. Ensure no special characters or spaces.',
        severity: 'Error',
      },
      {
        code: '5.1.8',
        name: 'Bad Sender Address',
        description: 'The sender address failed validation.',
        cause: 'The From address is missing or invalid.',
        fix: 'Ensure the sending application is providing a valid From address.',
        severity: 'Error',
      },
      {
        code: '5.1.10',
        name: 'Recipient Not Found',
        description: 'The recipient address does not exist in the destination system.',
        cause: 'Recipient was deleted, migrated, or never existed.',
        fix: 'Verify the recipient exists. If recently migrated, check routing and MX records.',
        severity: 'Error',
      },
      {
        code: '5.1.20',
        name: 'Too Many Recipients',
        description: 'The message has too many recipients.',
        cause: 'The number of recipients exceeds the per-message limit.',
        fix: 'Split the message into multiple sends. Default Exchange Online limit is 500 recipients per message.',
        severity: 'Warning',
      },
    ],
  },
  {
    category: 'Mailbox & Capacity (5.2.x)',
    codes: [
      {
        code: '5.2.1',
        name: 'Mailbox Not Accepting Messages',
        description: 'The recipient mailbox is not accepting messages at this time.',
        cause: 'Mailbox may be on litigation hold with delivery disabled, or the store is unmounted.',
        fix: 'Check mailbox status in Exchange Admin Center. Verify the mailbox database is mounted.',
        severity: 'Error',
      },
      {
        code: '5.2.2',
        name: 'Mailbox Full',
        description: 'The recipient mailbox has exceeded its storage limit.',
        cause: 'Mailbox quota exceeded.',
        fix: 'Ask the recipient to delete emails, or increase mailbox quota in Exchange Admin Center.',
        severity: 'Warning',
      },
      {
        code: '5.2.3',
        name: 'Message Too Large',
        description: 'The message exceeds the maximum allowed size for the recipient.',
        cause: 'Message size including attachments exceeds the limit set by the recipient organization.',
        fix: 'Reduce attachment size or use a file sharing service. Check message size limits in Exchange Admin Center.',
        severity: 'Warning',
      },
      {
        code: '5.2.4',
        name: 'Mailing List Expansion Problem',
        description: 'A distribution group could not be expanded.',
        cause: 'The distribution group has no members, is misconfigured, or the expansion server is unavailable.',
        fix: 'Verify the distribution group has members and is correctly configured.',
        severity: 'Error',
      },
      {
        code: '5.2.11',
        name: 'System Capacity Exceeded',
        description: 'The destination system has reached capacity.',
        cause: 'The receiving mail system is at maximum capacity.',
        fix: 'Retry later. If persistent, contact the recipient organization.',
        severity: 'Warning',
      },
      {
        code: '5.2.12',
        name: 'Recipient Per Hour Limit Exceeded',
        description: 'The recipient has received too many messages in the last hour.',
        cause: 'Per-recipient throttling limit reached.',
        fix: 'Wait and retry. If this is a distribution group receiving mass messages, review send limits.',
        severity: 'Warning',
      },
      {
        code: '5.2.14',
        name: 'Too Many Related Errors',
        description: 'Too many errors occurred during delivery.',
        cause: 'Multiple delivery failures have caused the session to be terminated.',
        fix: 'Review message headers for earlier errors in the session.',
        severity: 'Error',
      },
    ],
  },
  {
    category: 'System & Configuration (5.3.x)',
    codes: [
      {
        code: '5.3.0',
        name: 'Other or Undefined Mail System Status',
        description: 'An unspecified mail system error occurred.',
        cause: 'General transport error with no specific code.',
        fix: 'Check message headers and transport logs for more detail.',
        severity: 'Error',
      },
      {
        code: '5.3.2',
        name: 'System Not Accepting Messages',
        description: 'The destination system is not accepting messages.',
        cause: 'Receiving server is in maintenance mode, overloaded, or has a transport service issue.',
        fix: 'Retry later. Check Exchange transport service status on the destination server.',
        severity: 'Error',
      },
      {
        code: '5.3.3',
        name: 'Feature Not Supported',
        description: 'The requested mail feature is not supported by the destination.',
        cause: 'The destination server does not support a required SMTP extension.',
        fix: 'Check connector settings. Ensure required SMTP extensions are supported.',
        severity: 'Error',
      },
      {
        code: '5.3.4',
        name: 'Message Too Big for System',
        description: 'The message is too large for the overall system to process.',
        cause: 'Message size exceeds a system-wide transport limit.',
        fix: 'Reduce message size. Check system-level message size limits on both sending and receiving servers.',
        severity: 'Warning',
      },
      {
        code: '5.3.5',
        name: 'System Incorrectly Configured',
        description: 'The mail system is incorrectly configured.',
        cause: 'Misconfigured connector, accepted domain, or email address policy.',
        fix: 'Review Exchange transport configuration. Check accepted domains and send/receive connectors.',
        severity: 'Error',
      },
    ],
  },
  {
    category: 'Protocol Errors (5.5.x)',
    codes: [
      {
        code: '5.5.0',
        name: 'Underlying SMTP Protocol Error',
        description: 'An underlying SMTP protocol error occurred.',
        cause: 'General SMTP error often caused by network issues or server misconfiguration.',
        fix: 'Check transport logs for the full SMTP conversation.',
        severity: 'Error',
      },
      {
        code: '5.5.1',
        name: 'Invalid Command',
        description: 'An invalid SMTP command was issued.',
        cause: 'The sending server issued a command that is not recognized or not allowed.',
        fix: 'Check if the sending server supports the same SMTP version. Review connector settings.',
        severity: 'Error',
      },
      {
        code: '5.5.2',
        name: 'Send Hello First',
        description: 'The server requires a HELO/EHLO command before any other commands.',
        cause: 'The sending server skipped the EHLO greeting.',
        fix: 'Ensure the sending server properly initiates SMTP sessions with EHLO/HELO.',
        severity: 'Error',
      },
      {
        code: '5.5.3',
        name: 'Too Many Recipients',
        description: 'Too many recipients were specified in the RCPT TO commands.',
        cause: 'The per-message recipient limit was exceeded.',
        fix: 'Split into multiple messages. Exchange Online allows up to 500 recipients per message.',
        severity: 'Warning',
      },
      {
        code: '5.5.4',
        name: 'Invalid Domain Name',
        description: 'The domain name in the message is invalid.',
        cause: 'The domain portion of an address does not meet RFC requirements.',
        fix: 'Check domain name syntax in From or To addresses.',
        severity: 'Error',
      },
      {
        code: '5.5.5',
        name: 'Wrong Protocol Version',
        description: 'The server and client are using incompatible SMTP protocol versions.',
        cause: 'Protocol version mismatch between sending and receiving servers.',
        fix: 'Verify both servers support compatible SMTP versions and extensions.',
        severity: 'Error',
      },
      {
        code: '5.5.6',
        name: 'Invalid Message Content',
        description: 'The message contains invalid content that cannot be processed.',
        cause: 'Malformed headers, invalid encoding, or corrupted message body.',
        fix: 'Check message format and encoding. Ensure all required headers are present.',
        severity: 'Error',
      },
    ],
  },
  {
    category: 'Content & Encoding Errors (5.6.x)',
    codes: [
      {
        code: '5.6.0',
        name: 'Other or Undefined Media Error',
        description: 'An unspecified message content or media error occurred.',
        cause: 'General content error with no specific code.',
        fix: 'Check message content and encoding.',
        severity: 'Error',
      },
      {
        code: '5.6.1',
        name: 'Media Not Supported',
        description: 'The destination does not support the message media type.',
        cause: 'The message contains a MIME type or encoding not supported by the recipient.',
        fix: 'Convert the message to a universally supported format.',
        severity: 'Error',
      },
      {
        code: '5.6.2',
        name: 'Conversion Required and Prohibited',
        description: 'Message conversion is required but has been prohibited by policy.',
        cause: 'The message requires format conversion but the sending policy prohibits it.',
        fix: 'Review message format settings and content conversion policies.',
        severity: 'Error',
      },
      {
        code: '5.6.3',
        name: 'Conversion Required but Not Supported',
        description: 'Message conversion is required but the server does not support it.',
        cause: 'The message format cannot be converted by the receiving server.',
        fix: 'Send in a more universally supported format such as plain text or standard MIME.',
        severity: 'Error',
      },
      {
        code: '5.6.5',
        name: 'Conversion Failed',
        description: 'The message content conversion failed.',
        cause: 'Corrupt attachment, unsupported encoding, or conversion service error.',
        fix: 'Re-send the message without the problematic attachment, or convert it to a different format first.',
        severity: 'Error',
      },
      {
        code: '5.6.11',
        name: 'Invalid Characters',
        description: 'The message contains invalid characters.',
        cause: 'Non-ASCII characters in headers or body without proper encoding.',
        fix: 'Ensure the message is properly encoded. Use UTF-8 or quoted-printable encoding.',
        severity: 'Error',
      },
    ],
  },
  {
    category: 'Routing & Delivery (4.4.x / 5.4.x)',
    codes: [
      {
        code: '4.4.1',
        name: 'Connection Timed Out',
        description: 'The connection to the remote server timed out.',
        cause: 'Network issue, firewall blocking port 25, or destination server overloaded.',
        fix: 'Check network connectivity to the destination MX server. Verify port 25 is open.',
        severity: 'Warning',
      },
      {
        code: '4.4.2',
        name: 'Connection Dropped',
        description: 'The connection was dropped before delivery could complete.',
        cause: 'Network interruption, firewall timeout, or server-side disconnect.',
        fix: 'Usually retried automatically. Check for persistent network issues if recurring.',
        severity: 'Warning',
      },
      {
        code: '4.4.7',
        name: 'Message Expired - Delivery Timeout',
        description: 'The message could not be delivered within the time limit and has expired.',
        cause: 'Destination server unreachable, DNS failure, network issue, or receiving server rejecting connections.',
        fix: 'Check MX records for the destination domain. Verify the destination server is accepting connections on port 25. Check for firewall or IP blocks.',
        severity: 'Error',
      },
      {
        code: '4.4.9',
        name: 'Connection Reset',
        description: 'The connection was reset by the remote server.',
        cause: 'Destination server rejected the connection after it was established.',
        fix: 'Check if the sending IP is blocked by the destination. Review connector settings.',
        severity: 'Warning',
      },
      {
        code: '4.4.316',
        name: 'Connection Timed Out (Detailed)',
        description: 'The SMTP connection to the destination server timed out.',
        cause: 'Port 25 blocked by firewall, destination server overloaded, or network routing issue.',
        fix: 'Verify port 25 is not blocked. Test connectivity to the destination MX server.',
        severity: 'Error',
      },
      {
        code: '5.4.1',
        name: 'No Answer from Host',
        description: 'The destination server did not respond.',
        cause: 'MX record points to an unresponsive server.',
        fix: 'Verify MX records are correct and the destination mail server is running.',
        severity: 'Error',
      },
      {
        code: '5.4.4',
        name: 'Invalid Argument - Cannot Route',
        description: 'The next hop could not be determined.',
        cause: 'MX record missing, DNS resolution failure, or connector misconfiguration.',
        fix: 'Verify MX records and DNS resolution for the destination domain.',
        severity: 'Error',
      },
      {
        code: '5.4.6',
        name: 'Routing Loop Detected',
        description: 'A mail routing loop was detected.',
        cause: 'Connector misconfiguration causing messages to loop between servers.',
        fix: 'Review send and receive connectors. Check accepted domains configuration.',
        severity: 'Critical',
      },
      {
        code: '5.4.8',
        name: 'MX Record Points to Invalid Address',
        description: 'The MX record resolves to a private or loopback IP address.',
        cause: 'DNS misconfiguration where MX record points to an internal or invalid IP.',
        fix: 'Fix the MX record to point to a valid public mail server hostname.',
        severity: 'Critical',
      },
      {
        code: '5.4.14',
        name: 'Hop Count Exceeded',
        description: 'The message has been forwarded too many times.',
        cause: 'Mail loop or excessive forwarding rules.',
        fix: 'Check auto-forwarding rules on mailboxes and transport rules for loops.',
        severity: 'Critical',
      },
      {
        code: '5.4.300',
        name: 'Message Expired',
        description: 'The message queue expired before delivery.',
        cause: 'Persistent delivery failure over the retry period (default 2 days in Exchange Online).',
        fix: 'Investigate the underlying delivery failure. Check if the destination server was unavailable.',
        severity: 'Error',
      },
      {
        code: '5.4.310',
        name: 'DNS Domain Does Not Exist',
        description: 'The domain in the recipient address does not exist in DNS.',
        cause: 'The recipient domain has no DNS records, or the domain was deleted.',
        fix: 'Verify the recipient domain exists and has valid MX records.',
        severity: 'Error',
      },
      {
        code: '5.4.312',
        name: 'DNS MX Record Does Not Exist',
        description: 'The recipient domain does not have MX records.',
        cause: 'The domain exists but has no MX records configured.',
        fix: 'Verify MX records for the recipient domain. Check if the domain accepts email.',
        severity: 'Error',
      },
      {
        code: '5.4.316',
        name: 'Message Size Limit Exceeded',
        description: 'The message size exceeds the limit of the next hop.',
        cause: 'A server in the delivery path has a lower message size limit than the sender.',
        fix: 'Reduce message size. Identify which hop has the lower limit.',
        severity: 'Warning',
      },
    ],
  },
  {
    category: 'TLS & Certificate Errors (5.7.3xx / 4.7.x)',
    codes: [
      {
        code: '5.7.3',
        name: 'STARTTLS Required',
        description: 'The destination server requires TLS but the connection failed.',
        cause: 'TLS certificate issue on the receiving end, or connector configured to require TLS.',
        fix: 'Check the certificate on the destination mail server. Review connector TLS settings.',
        severity: 'Error',
      },
      {
        code: '5.7.321',
        name: 'Certificate Validation Failed',
        description: 'The destination server TLS certificate failed validation.',
        cause: 'Expired, self-signed, or mismatched certificate on the receiving server.',
        fix: 'Check the receiving server TLS certificate. If using a connector, you may need to disable certificate validation temporarily.',
        severity: 'Error',
      },
      {
        code: '5.7.322',
        name: 'Certificate Expired',
        description: 'The TLS certificate on the destination server has expired.',
        cause: 'The mail server certificate is past its expiration date.',
        fix: 'Renew the TLS certificate on the receiving mail server.',
        severity: 'Error',
      },
      {
        code: '5.7.323',
        name: 'TLS Required by Policy',
        description: 'The message was rejected because TLS is required by policy.',
        cause: 'A transport rule or connector requires TLS but the connection could not be established.',
        fix: 'Ensure both sides support TLS. Review connector TLS requirements.',
        severity: 'Error',
      },
      {
        code: '5.7.324',
        name: 'Certificate Does Not Match Domain',
        description: 'The TLS certificate does not match the destination domain.',
        cause: 'The CN or SAN on the certificate does not include the mail server hostname.',
        fix: 'Update the certificate to include the correct hostname, or adjust connector settings.',
        severity: 'Error',
      },
      {
        code: '5.7.325',
        name: 'Certificate Not Trusted',
        description: 'The TLS certificate is not trusted.',
        cause: 'The certificate is self-signed or the CA is not in the trust store.',
        fix: 'Use a certificate from a trusted public CA, or add the CA to the trust store.',
        severity: 'Error',
      },
      {
        code: '4.7.26',
        name: 'DMARC Policy Violation - Quarantine',
        description: 'Message quarantined due to DMARC policy.',
        cause: 'The message failed DMARC alignment and the policy is p=quarantine.',
        fix: 'Ensure SPF and DKIM are properly configured and aligned with the From domain.',
        severity: 'Warning',
      },
    ],
  },
  {
    category: 'Transient / Temporary Failures (4.x.x)',
    codes: [
      {
        code: '4.2.1',
        name: 'Mailbox Busy',
        description: 'The destination mailbox is temporarily busy.',
        cause: 'The mailbox is being accessed by another process or is temporarily locked.',
        fix: 'Retry delivery. Usually resolves automatically.',
        severity: 'Info',
      },
      {
        code: '4.2.2',
        name: 'Mailbox Full - Temporary',
        description: 'The mailbox is temporarily full.',
        cause: 'The recipient mailbox has exceeded its quota.',
        fix: 'Notify the recipient to free up space. Consider increasing quota.',
        severity: 'Warning',
      },
      {
        code: '4.3.1',
        name: 'Insufficient System Resources',
        description: 'The destination server is temporarily out of resources.',
        cause: 'Server disk space, memory, or queue is full.',
        fix: 'Usually self-resolving. If persistent, check destination server health.',
        severity: 'Warning',
      },
      {
        code: '4.3.2',
        name: 'Service Not Available',
        description: 'The destination mail service is temporarily unavailable.',
        cause: 'Server maintenance, overload, or temporary outage.',
        fix: 'Retry later. If persistent after 24 hours, investigate destination server availability.',
        severity: 'Warning',
      },
      {
        code: '4.6.5',
        name: 'Multi-Language Situation',
        description: 'A multi-language message could not be delivered temporarily.',
        cause: 'Language conversion error during delivery attempt.',
        fix: 'Retry delivery. If persistent, check message encoding settings.',
        severity: 'Info',
      },
      {
        code: '4.7.0',
        name: 'Certificate Expired - Temporary',
        description: 'TLS handshake failed temporarily due to certificate issue.',
        cause: 'Certificate validation failure during a transient TLS negotiation.',
        fix: 'Check TLS certificate validity. Will retry automatically.',
        severity: 'Warning',
      },
      {
        code: '4.7.1',
        name: 'Delivery Not Authorized - Temporary',
        description: 'The sending domain is temporarily not authorized to send.',
        cause: 'Temporary restriction on the sending domain, often due to reputation.',
        fix: 'Retry later. Check sending domain reputation if recurring.',
        severity: 'Warning',
      },
    ],
  },
  {
    category: 'Hybrid Exchange Errors',
    codes: [
      {
        code: '5.7.64',
        name: 'Hybrid - TenantAttribution Error',
        description: 'Mail flow between on-premises and Exchange Online failed due to connector attribution.',
        cause: 'The hybrid connector is not correctly attributed to the tenant.',
        fix: 'Re-run Hybrid Configuration Wizard. Verify the inbound connector in Exchange Online matches the on-premises certificate.',
        severity: 'Error',
      },
      {
        code: '5.7.124',
        name: 'Not Authorized - Hybrid Connector',
        description: 'The sending server is not authorized to use the hybrid send connector.',
        cause: 'The on-premises server IP or certificate is not matched in the Exchange Online inbound connector.',
        fix: 'Update the inbound connector in Exchange Online to trust the on-premises server certificate or IP range.',
        severity: 'Error',
      },
      {
        code: '5.7.321',
        name: 'Hybrid - TLS Certificate Mismatch',
        description: 'TLS certificate validation failed on the hybrid connector.',
        cause: 'The on-premises Exchange server certificate does not match the hybrid connector configuration.',
        fix: 'Ensure the on-premises Exchange certificate matches what is configured in the Exchange Online connector. Re-run Hybrid Configuration Wizard if needed.',
        severity: 'Error',
      },
      {
        code: '5.4.6',
        name: 'Hybrid - Mail Loop',
        description: 'Mail is looping between on-premises and Exchange Online.',
        cause: 'Accepted domain misconfiguration or connector routing loop in hybrid environment.',
        fix: 'Verify accepted domain type (Authoritative vs Internal Relay) in Exchange Online and on-premises. Check connector routing.',
        severity: 'Critical',
      },
      {
        code: '5.1.1',
        name: 'Hybrid - Recipient Not Found',
        description: 'The recipient is not found in either on-premises or Exchange Online.',
        cause: 'User not synced via Azure AD Connect, or mailbox not migrated.',
        fix: 'Verify Azure AD Connect sync status. Check if the mailbox exists in either environment.',
        severity: 'Error',
      },
    ],
  },
];
