export const ndrCategories: {
  category: string
  codes: {
    code: string
    name: string
    description: string
    cause: string
    fix: string
    severity: 'Info' | 'Warning' | 'Error' | 'Critical'
  }[]
}[] = [
  {
    category: 'Authentication & Authorization (5.7.x)',
    codes: [
      {
        code: '5.7.1',
        name: 'Delivery Not Authorized',
        description: 'The sending address is not permitted to send to this recipient.',
        cause: 'The recipient has restrictions on who can send to them, or the sender is blocked by a transport rule.',
        fix: 'Check recipient delivery restrictions in Exchange Admin Center. Check transport rules for blocks on the sender domain or address.',
        severity: 'Error',
      },
      {
        code: '5.7.23',
        name: 'SPF Validation Failed',
        description: 'The message was rejected because the sending domain SPF record does not include the sending server.',
        cause: 'The sending IP is not listed in the domain SPF record, or SPF is misconfigured.',
        fix: 'Verify the sending server IP is included in the SPF record. Check for SPF flattening issues or too many DNS lookups (max 10).',
        severity: 'Error',
      },
      {
        code: '5.7.25',
        name: 'SPF Permanent Error',
        description: 'A permanent SPF error occurred during validation.',
        cause: 'SPF record has a syntax error, exceeds DNS lookup limit, or returns a PermError.',
        fix: 'Validate SPF record syntax using an SPF checker. Reduce DNS lookups to under 10.',
        severity: 'Error',
      },
      {
        code: '5.7.26',
        name: 'SPF Validation Failed (Forwarded)',
        description: 'Message failed SPF because it was forwarded and the forwarding server is not in the SPF record.',
        cause: 'Email forwarding breaks SPF alignment. The forwarder IP is not in the original sender SPF record.',
        fix: 'Implement DMARC with DKIM signing so forwarded messages pass DKIM even when SPF fails. Use SRS (Sender Rewriting Scheme) on the forwarding server.',
        severity: 'Warning',
      },
      {
        code: '5.7.57',
        name: 'Client Not Authenticated',
        description: 'The SMTP client was not authenticated and is not permitted to relay.',
        cause: 'Application or device attempting to relay without proper authentication.',
        fix: 'Configure SMTP AUTH on the sending application. Use a connector or dedicated relay with proper credentials.',
        severity: 'Error',
      },
      {
        code: '5.7.60',
        name: 'SMTP Client Does Not Have Permission',
        description: 'The client does not have permission to submit mail to this server.',
        cause: 'The connector or receive connector is not configured to accept connections from this IP.',
        fix: 'Add the sending IP to the appropriate receive connector in Exchange Admin Center.',
        severity: 'Error',
      },
      {
        code: '5.7.64',
        name: 'TenantAttribution - Tenant Relay Blocked',
        description: 'Your organization has blocked outbound relay from this source.',
        cause: 'Connector configuration issue or tenant policy blocking relay. In hybrid environments, the on-premises hybrid connector may not be correctly attributed to the tenant.',
        fix: 'Review outbound connectors in Exchange Admin Center. Check tenant relay settings. For hybrid: re-run the Hybrid Configuration Wizard and verify the inbound connector in EXO matches the on-premises certificate.',
        severity: 'Error',
      },
      {
        code: '5.7.67',
        name: 'Sender Not Authenticated (Inbound Connector)',
        description: 'The inbound connector requires authentication but the sender did not authenticate.',
        cause: 'Inbound connector is configured to require certificate or IP-based authentication.',
        fix: 'Check inbound connector configuration. Ensure the sending server meets the authentication requirements.',
        severity: 'Error',
      },
      {
        code: '5.7.133',
        name: 'Sender Not in Group',
        description: 'The sender is not a member of the distribution group required to send to this recipient.',
        cause: 'The recipient is a group with membership-restricted sending.',
        fix: 'Add the sender to the allowed senders list on the distribution group, or adjust group delivery restrictions.',
        severity: 'Warning',
      },
      {
        code: '5.7.134',
        name: 'Sender Not Permitted for Mailbox',
        description: 'The sender is not permitted to send to this mailbox.',
        cause: 'Mailbox has specific sender restrictions configured.',
        fix: 'Check the mailbox delivery restrictions in Exchange Admin Center under mailbox > mail flow settings.',
        severity: 'Warning',
      },
      {
        code: '5.7.135',
        name: 'Sender Not in Safe Senders',
        description: 'The recipient only accepts mail from their safe senders list.',
        cause: 'The mailbox is configured to only accept from contacts or safe senders.',
        fix: 'Have the recipient add the sender to their safe senders list, or adjust mailbox policy.',
        severity: 'Warning',
      },
      {
        code: '5.7.136',
        name: 'Sender Not Permitted (User Policy)',
        description: 'Mail rejected per sender policy for this user.',
        cause: 'User-level policy is blocking the sender.',
        fix: 'Review user-level mail flow rules and safe sender configurations.',
        severity: 'Warning',
      },
      {
        code: '5.7.501',
        name: 'Access Denied - Spam Policy',
        description: 'The sending IP or domain is blocked due to spam policy.',
        cause: 'IP reputation or spam score triggered a block.',
        fix: 'Check IP reputation at MXToolbox or Microsoft SNDS. Submit delisting request if IP is legitimate.',
        severity: 'Error',
      },
      {
        code: '5.7.503',
        name: 'Access Denied - Banned Sender',
        description: 'The sending account or domain has been banned.',
        cause: 'The sender has been explicitly blocked by Microsoft or the recipient tenant.',
        fix: 'Use Microsoft Sender Support portal to request a review.',
        severity: 'Critical',
      },
      {
        code: '5.7.505',
        name: 'Access Denied - Sending Account Suspended',
        description: 'The sending account has been suspended for sending spam.',
        cause: 'Account was compromised and used to send spam, triggering an outbound spam block.',
        fix: 'Investigate the account for compromise. Reset credentials, enable MFA, review sent items. Unblock via Security & Compliance Center > Review restricted users.',
        severity: 'Critical',
      },
      {
        code: '5.7.506',
        name: 'Bad HELO',
        description: 'The server rejected the connection because of a bad HELO/EHLO greeting.',
        cause: 'The sending server is using a hostname in HELO/EHLO that does not match its PTR record or is a private IP.',
        fix: 'Ensure the sending server uses its public FQDN in HELO/EHLO. Verify PTR record matches the FQDN.',
        severity: 'Error',
      },
      {
        code: '5.7.508',
        name: 'Access Denied - IP Sending Too Fast',
        description: 'The sending IP is throttled for sending too many messages.',
        cause: 'The IP is sending volume above the allowed threshold.',
        fix: 'Reduce sending rate. If legitimate bulk mail, use a dedicated IP with a warm-up period.',
        severity: 'Warning',
      },
      {
        code: '5.7.509',
        name: 'DMARC Policy Violation - Reject',
        description: 'Message rejected due to DMARC policy.',
        cause: 'The message failed DMARC alignment and the policy is p=reject.',
        fix: 'Verify SPF includes the sending IP and DKIM is signing with the correct domain.',
        severity: 'Error',
      },
      {
        code: '5.7.510',
        name: 'Access Denied - Message Does Not Meet IPv6 Requirements',
        description: 'Messages sent via IPv6 must pass reverse DNS lookup.',
        cause: 'The sending IPv6 address does not have a valid PTR record.',
        fix: 'Configure a PTR record for the sending IPv6 address, or send via IPv4.',
        severity: 'Error',
      },
      {
        code: '5.7.511',
        name: 'Access Denied - Banned Sender',
        description: 'This sender is banned from sending mail.',
        cause: 'The sender has been explicitly blocked.',
        fix: 'Review blocked senders list in anti-spam policies.',
        severity: 'Error',
      },
      {
        code: '5.7.512',
        name: 'Access Denied - Message Must Be RFC 5321 Compliant',
        description: 'The message does not comply with RFC 5321 requirements.',
        cause: 'Missing or malformed required SMTP headers.',
        fix: 'Ensure the sending application generates RFC-compliant messages with valid From, To, and Date headers.',
        severity: 'Error',
      },
      {
        code: '5.7.606',
        name: 'Access Denied - Banned Sending IP',
        description: 'The sending IP is on Microsoft block list.',
        cause: 'The IP has been flagged for sending spam or malicious content.',
        fix: 'Submit a delisting request at https://sender.office.com. Investigate why the IP was flagged.',
        severity: 'Critical',
      },
      {
        code: '5.7.700',
        name: 'Access Denied - Tenant Policy',
        description: 'Message rejected due to a tenant-level policy.',
        cause: 'A tenant-wide transport rule or policy is blocking the message.',
        fix: 'Review transport rules in Exchange Admin Center > Mail Flow > Rules.',
        severity: 'Error',
      },
      {
        code: '5.7.708',
        name: 'Access Denied - Tenant Blocked',
        description: 'Service not available. Access denied. Tenant is blocked.',
        cause: 'The sending tenant has been blocked by Microsoft, often due to compromised accounts sending spam.',
        fix: 'Contact Microsoft Support. Review outbound spam reports and compromised accounts.',
        severity: 'Critical',
      },
      {
        code: '5.7.750',
        name: 'Client Blocked - Too Many Spam Complaints',
        description: 'The sending domain or IP is blocked due to excessive spam complaints.',
        cause: 'Recipients have marked too many messages as spam.',
        fix: 'Review mailing list hygiene. Implement unsubscribe mechanisms. Check spam complaint rate.',
        severity: 'Critical',
      },
      {
        code: '5.7.900',
        name: 'Message Blocked - Safe Attachments',
        description: 'Microsoft Defender Safe Attachments blocked the message.',
        cause: 'An attachment was determined to be malicious by Safe Attachments detonation.',
        fix: 'The attachment contains malware. Do not send. If false positive, review Safe Attachments policy and submit to Microsoft.',
        severity: 'Critical',
      },
      {
        code: '5.7.901',
        name: 'Message Blocked - Safe Links',
        description: 'Microsoft Defender Safe Links blocked the message.',
        cause: 'A URL in the message was flagged as malicious.',
        fix: 'Review the URLs in the message. If false positive, submit to Microsoft via the Submissions portal.',
        severity: 'Critical',
      },
      {
        code: '5.7.13',
        name: 'User Account Is Disabled',
        description: 'The recipient mailbox is disabled or the account has been blocked from sign-in.',
        cause: 'The mailbox owner account is disabled in Active Directory or Microsoft Entra ID, often after a leaver process. The mailbox itself may still exist but cannot accept mail.',
        fix: 'Re-enable the user account if the disable was unintentional. If the user has truly left, convert the mailbox to a shared mailbox or set up a forward to delegate ownership.',
        severity: 'Error',
      },
      {
        code: '5.7.50',
        name: 'Spoofing Detected (Composite Authentication Failure)',
        description: 'The message failed composite authentication (SPF + DKIM + DMARC) and was identified as a spoofing attempt by Defender for Office 365.',
        cause: 'The sending domain failed SPF/DKIM/DMARC, or the From header does not match the authenticated sender. Related codes 5.7.51-5.7.54 cover variant scenarios (intra-org spoof, brand impersonation, user impersonation, etc.).',
        fix: 'For legitimate senders: fix SPF, DKIM, and DMARC alignment on the sending domain. For false positives: add the sender or domain to the Tenant Allow/Block List or anti-spoofing override after verifying legitimacy.',
        severity: 'Error',
      },
      {
        code: '5.7.230',
        name: 'Access Denied - No Permissions for Organization',
        description: 'The sender does not have permissions to send to this organization.',
        cause: 'A connector restriction or organization-wide policy is blocking the sender. Often seen with partner-restricted inbound connectors.',
        fix: 'Review inbound connectors and organization-level transport rules. Verify the sender domain is on the allow list if a partner connector is in use.',
        severity: 'Error',
      },
      {
        code: '5.7.350',
        name: 'Remote Server Returned Message As Spam',
        description: 'The destination server identified your outbound message as spam and rejected it.',
        cause: 'Your sending IP or domain has poor reputation, the message content triggered a spam filter on the recipient side, or SPF/DKIM/DMARC alignment failed at the recipient.',
        fix: 'Check sender reputation on senderscore.org and Microsoft SNDS. Verify SPF/DKIM/DMARC are correctly published. Review message content for spam triggers. If recurring, request the recipient admin allow-list your domain.',
        severity: 'Error',
      },
      {
        code: '5.7.520',
        name: 'Phishing Detected by Defender for Office 365',
        description: 'Microsoft Defender for Office 365 identified the message as a phishing attempt and blocked it.',
        cause: 'Message content, URLs, sender behavior, or impersonation signals triggered Defender phishing detection.',
        fix: 'For false positives: submit the message to Microsoft via the Submissions portal as "Should not have been blocked". Add legitimate senders to the Tenant Allow/Block List after review. Do not bypass without verification — this is high-confidence phishing detection.',
        severity: 'Critical',
      },
      {
        code: '5.7.704',
        name: 'Remote Server Did Not Accept Message',
        description: 'The destination server rejected the message for a compliance, policy, or recipient-side reason.',
        cause: 'Recipient-side mail flow rule, conditional access policy, journaling/archive issue, or third-party security gateway rejection.',
        fix: 'Contact the recipient organization admin — the rejection is on their side. Provide them the full NDR header so they can locate the rejecting system or rule.',
        severity: 'Error',
      },
    ],
  },
  {
    category: 'DKIM Errors (5.7.2xx)',
    codes: [
      {
        code: '5.7.200',
        name: 'DKIM Signature Missing',
        description: 'The message does not have a DKIM signature and the policy requires one.',
        cause: 'Sending domain has a DKIM policy requiring signatures but the message was not signed.',
        fix: 'Enable DKIM signing for the sending domain in Exchange Admin Center or DNS.',
        severity: 'Error',
      },
      {
        code: '5.7.201',
        name: 'DKIM Signature Verification Failed',
        description: 'The DKIM signature on the message could not be verified.',
        cause: 'DKIM public key in DNS does not match the private key used to sign, or the message was modified in transit.',
        fix: 'Verify DKIM selector DNS records are correct. Re-rotate DKIM keys if necessary.',
        severity: 'Error',
      },
      {
        code: '5.7.202',
        name: 'DKIM Key Revoked',
        description: 'The DKIM key used to sign the message has been revoked.',
        cause: 'The DKIM public key has been removed from DNS or set to p= (empty).',
        fix: 'Publish a new DKIM key pair and update the DNS TXT record.',
        severity: 'Error',
      },
      {
        code: '5.7.203',
        name: 'DKIM Key Not Found',
        description: 'The DKIM selector referenced in the signature was not found in DNS.',
        cause: 'The selector DNS record is missing or the selector in the signature is incorrect.',
        fix: 'Verify the DKIM selector TXT record exists in DNS for the signing domain.',
        severity: 'Error',
      },
    ],
  },
  {
    category: 'Recipient Issues (5.1.x)',
    codes: [
      {
        code: '5.1.0',
        name: 'Sender Denied',
        description: 'The sender address was rejected by the remote server.',
        cause: 'Sending address does not exist, is malformed, or is on a block list.',
        fix: 'Verify the sender address exists and is valid. Check outbound spam filter for blocked senders.',
        severity: 'Error',
      },
      {
        code: '5.1.1',
        name: 'Bad Destination Mailbox Address',
        description: 'The recipient email address does not exist.',
        cause: 'The address was mistyped, the mailbox was deleted, or the user never existed. In hybrid environments, the user may not have synced via Azure AD Connect or the mailbox was not migrated.',
        fix: 'Verify the recipient address is correct. Check if the mailbox was recently deleted or renamed. For hybrid: verify Azure AD Connect sync status and check that the mailbox exists in either on-premises or Exchange Online.',
        severity: 'Error',
      },
      {
        code: '5.1.2',
        name: 'Invalid X.400 Address',
        description: 'The recipient has a non-SMTP address that could not be resolved.',
        cause: 'Legacy X.400 address format issue.',
        fix: 'Update the recipient address to use standard SMTP format.',
        severity: 'Error',
      },
      {
        code: '5.1.3',
        name: 'Invalid Recipient Address',
        description: 'The recipient address is syntactically invalid.',
        cause: 'Malformed email address in the To, CC, or BCC field.',
        fix: 'Check the recipient address for typos or invalid characters.',
        severity: 'Error',
      },
      {
        code: '5.1.4',
        name: 'Destination Mailbox Address Ambiguous',
        description: 'Multiple recipients match the address.',
        cause: 'Duplicate email address or proxy address conflict in Active Directory.',
        fix: 'Check for duplicate proxy addresses in Exchange or Azure AD.',
        severity: 'Error',
      },
      {
        code: '5.1.6',
        name: 'Destination Mailbox Address Invalid',
        description: 'The destination mailbox address is invalid.',
        cause: 'The address exists in AD but the mailbox is not properly configured.',
        fix: 'Verify the mailbox is properly provisioned in Exchange.',
        severity: 'Error',
      },
      {
        code: '5.1.7',
        name: 'Invalid Address',
        description: 'The sender or recipient address is malformed.',
        cause: 'Invalid characters or format in the email address.',
        fix: 'Check the address format. Ensure no special characters or spaces.',
        severity: 'Error',
      },
      {
        code: '5.1.8',
        name: 'Bad Sender Address',
        description: 'The sender address failed validation.',
        cause: 'The From address is missing or invalid.',
        fix: 'Ensure the sending application is providing a valid From address.',
        severity: 'Error',
      },
      {
        code: '5.1.10',
        name: 'Recipient Not Found',
        description: 'The recipient address does not exist in the destination system.',
        cause: 'Recipient was deleted, migrated, or never existed.',
        fix: 'Verify the recipient exists. If recently migrated, check routing and MX records.',
        severity: 'Error',
      },
      {
        code: '5.1.20',
        name: 'Too Many Recipients',
        description: 'The message has too many recipients.',
        cause: 'The number of recipients exceeds the per-message limit.',
        fix: 'Split the message into multiple sends. Default Exchange Online limit is 500 recipients per message.',
        severity: 'Warning',
      },
      {
        code: '5.1.5',
        name: 'Destination Address Valid - Routing Failed',
        description: 'The recipient address is syntactically valid but cannot be resolved to a deliverable mailbox.',
        cause: 'The address exists in directory but its mailbox is not provisioned, has been moved, or the routing destination is unreachable. Sometimes appears mid-migration before the target mailbox is fully ready.',
        fix: 'Verify the recipient mailbox is fully provisioned. If a migration is in progress, wait for completion or check the mailbox is in the correct location. Confirm accepted domain configuration.',
        severity: 'Error',
      },
    ],
  },
  {
    category: 'Mailbox & Capacity (5.2.x)',
    codes: [
      {
        code: '5.2.1',
        name: 'Mailbox Not Accepting Messages',
        description: 'The recipient mailbox is not accepting messages at this time.',
        cause: 'Mailbox may be on litigation hold with delivery disabled, or the store is unmounted.',
        fix: 'Check mailbox status in Exchange Admin Center. Verify the mailbox database is mounted.',
        severity: 'Error',
      },
      {
        code: '5.2.2',
        name: 'Mailbox Full',
        description: 'The recipient mailbox has exceeded its storage limit.',
        cause: 'Mailbox quota exceeded.',
        fix: 'Ask the recipient to delete emails, or increase mailbox quota in Exchange Admin Center.',
        severity: 'Warning',
      },
      {
        code: '5.2.3',
        name: 'Message Too Large',
        description: 'The message exceeds the maximum allowed size for the recipient.',
        cause: 'Message size including attachments exceeds the limit set by the recipient organization.',
        fix: 'Reduce attachment size or use a file sharing service. Check message size limits in Exchange Admin Center.',
        severity: 'Warning',
      },
      {
        code: '5.2.4',
        name: 'Mailing List Expansion Problem',
        description: 'A distribution group could not be expanded.',
        cause: 'The distribution group has no members, is misconfigured, or the expansion server is unavailable.',
        fix: 'Verify the distribution group has members and is correctly configured.',
        severity: 'Error',
      },
      {
        code: '5.2.11',
        name: 'System Capacity Exceeded',
        description: 'The destination system has reached capacity.',
        cause: 'The receiving mail system is at maximum capacity.',
        fix: 'Retry later. If persistent, contact the recipient organization.',
        severity: 'Warning',
      },
      {
        code: '5.2.12',
        name: 'Recipient Per Hour Limit Exceeded',
        description: 'The recipient has received too many messages in the last hour.',
        cause: 'Per-recipient throttling limit reached.',
        fix: 'Wait and retry. If this is a distribution group receiving mass messages, review send limits.',
        severity: 'Warning',
      },
      {
        code: '5.2.14',
        name: 'Too Many Related Errors',
        description: 'Too many errors occurred during delivery.',
        cause: 'Multiple delivery failures have caused the session to be terminated.',
        fix: 'Review message headers for earlier errors in the session.',
        severity: 'Error',
      },
      {
        code: '5.2.121',
        name: 'Recipient Storage Quota Exceeded (M365)',
        description: 'The Microsoft 365 recipient mailbox is over its storage quota.',
        cause: 'The recipient mailbox has hit its prohibit-receive quota. This is the M365-specific variant of 5.2.2.',
        fix: 'Have the recipient empty Deleted Items, archive old mail, or have an admin temporarily raise the mailbox quota in the M365 admin center. Check the mailbox archive policy.',
        severity: 'Error',
      },
    ],
  },
  {
    category: 'System & Configuration (5.3.x)',
    codes: [
      {
        code: '5.3.0',
        name: 'Other or Undefined Mail System Status',
        description: 'An unspecified mail system error occurred.',
        cause: 'General transport error with no specific code.',
        fix: 'Check message headers and transport logs for more detail.',
        severity: 'Error',
      },
      {
        code: '5.3.2',
        name: 'System Not Accepting Messages',
        description: 'The destination system is not accepting messages.',
        cause: 'Receiving server is in maintenance mode, overloaded, or has a transport service issue.',
        fix: 'Retry later. Check Exchange transport service status on the destination server.',
        severity: 'Error',
      },
      {
        code: '5.3.3',
        name: 'Feature Not Supported',
        description: 'The requested mail feature is not supported by the destination.',
        cause: 'The destination server does not support a required SMTP extension.',
        fix: 'Check connector settings. Ensure required SMTP extensions are supported.',
        severity: 'Error',
      },
      {
        code: '5.3.4',
        name: 'Message Too Big for System',
        description: 'The message is too large for the overall system to process.',
        cause: 'Message size exceeds a system-wide transport limit.',
        fix: 'Reduce message size. Check system-level message size limits on both sending and receiving servers.',
        severity: 'Warning',
      },
      {
        code: '5.3.5',
        name: 'System Incorrectly Configured',
        description: 'The mail system is incorrectly configured.',
        cause: 'Misconfigured connector, accepted domain, or email address policy.',
        fix: 'Review Exchange transport configuration. Check accepted domains and send/receive connectors.',
        severity: 'Error',
      },
    ],
  },
  {
    category: 'Protocol Errors (5.5.x)',
    codes: [
      {
        code: '5.5.0',
        name: 'Underlying SMTP Protocol Error',
        description: 'An underlying SMTP protocol error occurred.',
        cause: 'General SMTP error often caused by network issues or server misconfiguration.',
        fix: 'Check transport logs for the full SMTP conversation.',
        severity: 'Error',
      },
      {
        code: '5.5.1',
        name: 'Invalid Command',
        description: 'An invalid SMTP command was issued.',
        cause: 'The sending server issued a command that is not recognized or not allowed.',
        fix: 'Check if the sending server supports the same SMTP version. Review connector settings.',
        severity: 'Error',
      },
      {
        code: '5.5.2',
        name: 'Send Hello First',
        description: 'The server requires a HELO/EHLO command before any other commands.',
        cause: 'The sending server skipped the EHLO greeting.',
        fix: 'Ensure the sending server properly initiates SMTP sessions with EHLO/HELO.',
        severity: 'Error',
      },
      {
        code: '5.5.3',
        name: 'Too Many Recipients',
        description: 'Too many recipients were specified in the RCPT TO commands.',
        cause: 'The per-message recipient limit was exceeded.',
        fix: 'Split into multiple messages. Exchange Online allows up to 500 recipients per message.',
        severity: 'Warning',
      },
      {
        code: '5.5.4',
        name: 'Invalid Domain Name',
        description: 'The domain name in the message is invalid.',
        cause: 'The domain portion of an address does not meet RFC requirements.',
        fix: 'Check domain name syntax in From or To addresses.',
        severity: 'Error',
      },
      {
        code: '5.5.5',
        name: 'Wrong Protocol Version',
        description: 'The server and client are using incompatible SMTP protocol versions.',
        cause: 'Protocol version mismatch between sending and receiving servers.',
        fix: 'Verify both servers support compatible SMTP versions and extensions.',
        severity: 'Error',
      },
      {
        code: '5.5.6',
        name: 'Invalid Message Content',
        description: 'The message contains invalid content that cannot be processed.',
        cause: 'Malformed headers, invalid encoding, or corrupted message body.',
        fix: 'Check message format and encoding. Ensure all required headers are present.',
        severity: 'Error',
      },
    ],
  },
  {
    category: 'Content & Encoding Errors (5.6.x)',
    codes: [
      {
        code: '5.6.0',
        name: 'Other or Undefined Media Error',
        description: 'An unspecified message content or media error occurred.',
        cause: 'General content error with no specific code.',
        fix: 'Check message content and encoding.',
        severity: 'Error',
      },
      {
        code: '5.6.1',
        name: 'Media Not Supported',
        description: 'The destination does not support the message media type.',
        cause: 'The message contains a MIME type or encoding not supported by the recipient.',
        fix: 'Convert the message to a universally supported format.',
        severity: 'Error',
      },
      {
        code: '5.6.2',
        name: 'Conversion Required and Prohibited',
        description: 'Message conversion is required but has been prohibited by policy.',
        cause: 'The message requires format conversion but the sending policy prohibits it.',
        fix: 'Review message format settings and content conversion policies.',
        severity: 'Error',
      },
      {
        code: '5.6.3',
        name: 'Conversion Required but Not Supported',
        description: 'Message conversion is required but the server does not support it.',
        cause: 'The message format cannot be converted by the receiving server.',
        fix: 'Send in a more universally supported format such as plain text or standard MIME.',
        severity: 'Error',
      },
      {
        code: '5.6.5',
        name: 'Conversion Failed',
        description: 'The message content conversion failed.',
        cause: 'Corrupt attachment, unsupported encoding, or conversion service error.',
        fix: 'Re-send the message without the problematic attachment, or convert it to a different format first.',
        severity: 'Error',
      },
      {
        code: '5.6.11',
        name: 'Invalid Characters',
        description: 'The message contains invalid characters.',
        cause: 'Non-ASCII characters in headers or body without proper encoding.',
        fix: 'Ensure the message is properly encoded. Use UTF-8 or quoted-printable encoding.',
        severity: 'Error',
      },
      {
        code: '5.6.7',
        name: 'Unsupported Content Type',
        description: 'The message contains a content type that the destination does not allow.',
        cause: 'Recipient policy blocks the MIME type or attachment format. Often hit by encrypted/signed S/MIME or certain script content types.',
        fix: 'Remove or repackage the offending content. Check the recipient organization Common Attachment Filter and any custom transport rules blocking content types.',
        severity: 'Error',
      },
      {
        code: '5.6.8',
        name: 'Mailbox Cannot Accept Message - Conversion Required',
        description: 'The recipient mailbox cannot accept the message in its current format and requires conversion.',
        cause: 'Format conversion failure between MIME, MAPI, and TNEF, often when sending to legacy systems or non-Exchange recipients.',
        fix: 'Re-send in plain text or HTML format (avoid Rich Text / TNEF). Configure remote domain settings to convert TNEF to MIME for the destination domain.',
        severity: 'Error',
      },
    ],
  },
  {
    category: 'Routing & Delivery (4.4.x / 5.4.x)',
    codes: [
      {
        code: '4.4.1',
        name: 'Connection Timed Out',
        description: 'The connection to the remote server timed out.',
        cause: 'Network issue, firewall blocking port 25, or destination server overloaded.',
        fix: 'Check network connectivity to the destination MX server. Verify port 25 is open.',
        severity: 'Warning',
      },
      {
        code: '4.4.2',
        name: 'Connection Dropped',
        description: 'The connection was dropped before delivery could complete.',
        cause: 'Network interruption, firewall timeout, or server-side disconnect.',
        fix: 'Usually retried automatically. Check for persistent network issues if recurring.',
        severity: 'Warning',
      },
      {
        code: '4.4.7',
        name: 'Message Expired - Delivery Timeout',
        description: 'The message could not be delivered within the time limit and has expired.',
        cause: 'Destination server unreachable, DNS failure, network issue, or receiving server rejecting connections.',
        fix: 'Check MX records for the destination domain. Verify the destination server is accepting connections on port 25. Check for firewall or IP blocks.',
        severity: 'Error',
      },
      {
        code: '4.4.9',
        name: 'Connection Reset',
        description: 'The connection was reset by the remote server.',
        cause: 'Destination server rejected the connection after it was established.',
        fix: 'Check if the sending IP is blocked by the destination. Review connector settings.',
        severity: 'Warning',
      },
      {
        code: '4.4.316',
        name: 'Connection Timed Out (Detailed)',
        description: 'The SMTP connection to the destination server timed out.',
        cause: 'Port 25 blocked by firewall, destination server overloaded, or network routing issue.',
        fix: 'Verify port 25 is not blocked. Test connectivity to the destination MX server.',
        severity: 'Error',
      },
      {
        code: '5.4.1',
        name: 'No Answer from Host',
        description: 'The destination server did not respond.',
        cause: 'MX record points to an unresponsive server.',
        fix: 'Verify MX records are correct and the destination mail server is running.',
        severity: 'Error',
      },
      {
        code: '5.4.4',
        name: 'Invalid Argument - Cannot Route',
        description: 'The next hop could not be determined.',
        cause: 'MX record missing, DNS resolution failure, or connector misconfiguration.',
        fix: 'Verify MX records and DNS resolution for the destination domain.',
        severity: 'Error',
      },
      {
        code: '5.4.6',
        name: 'Routing Loop Detected',
        description: 'A mail routing loop was detected.',
        cause: 'Connector misconfiguration causing messages to loop between servers. In hybrid environments, this is usually caused by accepted domain misconfiguration (Authoritative vs Internal Relay) on either side.',
        fix: 'Review send and receive connectors. Check accepted domains configuration. For hybrid: verify accepted domain type matches on both EXO and on-premises, and confirm connector routing is not sending mail back to the source.',
        severity: 'Critical',
      },
      {
        code: '5.4.8',
        name: 'MX Record Points to Invalid Address',
        description: 'The MX record resolves to a private or loopback IP address.',
        cause: 'DNS misconfiguration where MX record points to an internal or invalid IP.',
        fix: 'Fix the MX record to point to a valid public mail server hostname.',
        severity: 'Critical',
      },
      {
        code: '5.4.14',
        name: 'Hop Count Exceeded',
        description: 'The message has been forwarded too many times.',
        cause: 'Mail loop or excessive forwarding rules.',
        fix: 'Check auto-forwarding rules on mailboxes and transport rules for loops.',
        severity: 'Critical',
      },
      {
        code: '5.4.300',
        name: 'Message Expired',
        description: 'The message queue expired before delivery.',
        cause: 'Persistent delivery failure over the retry period (default 2 days in Exchange Online).',
        fix: 'Investigate the underlying delivery failure. Check if the destination server was unavailable.',
        severity: 'Error',
      },
      {
        code: '5.4.310',
        name: 'DNS Domain Does Not Exist',
        description: 'The domain in the recipient address does not exist in DNS.',
        cause: 'The recipient domain has no DNS records, or the domain was deleted.',
        fix: 'Verify the recipient domain exists and has valid MX records.',
        severity: 'Error',
      },
      {
        code: '5.4.312',
        name: 'DNS MX Record Does Not Exist',
        description: 'The recipient domain does not have MX records.',
        cause: 'The domain exists but has no MX records configured.',
        fix: 'Verify MX records for the recipient domain. Check if the domain accepts email.',
        severity: 'Error',
      },
      {
        code: '5.4.316',
        name: 'Message Size Limit Exceeded',
        description: 'The message size exceeds the limit of the next hop.',
        cause: 'A server in the delivery path has a lower message size limit than the sender.',
        fix: 'Reduce message size. Identify which hop has the lower limit.',
        severity: 'Warning',
      },
      {
        code: '5.4.0',
        name: 'Generic Routing Failure',
        description: 'A non-specific routing or network error occurred during delivery.',
        cause: 'Catchall routing failure. Often DNS issues, unreachable next hop, or transient network problems that did not fit a more specific code.',
        fix: 'Check DNS resolution for the destination domain. Verify connectors are healthy. Inspect the full NDR header for the actual failing component.',
        severity: 'Error',
      },
      {
        code: '5.4.2',
        name: 'Bad Connection',
        description: 'The connection to the destination server was lost during delivery.',
        cause: 'Network instability, firewall reset, or destination server dropping connections mid-session.',
        fix: 'Retry — often transient. If persistent, check firewall, routing, and any IDS/IPS dropping SMTP connections. Run Test-NetConnection from the source to the destination.',
        severity: 'Error',
      },
      {
        code: '5.4.7',
        name: 'Delivery Time Expired',
        description: 'The message could not be delivered within the configured timeout window.',
        cause: 'Repeated transient failures (4.x.x) accumulated past the retry timeout. Often follows a smarthost outage, DNS problem, or sustained recipient-side throttling.',
        fix: 'Investigate why retries kept failing — check recipient server health, DNS, and any rate limiting. The original message must be re-sent; it cannot be re-queued from the NDR.',
        severity: 'Error',
      },
      {
        code: '5.4.10',
        name: 'DNS Error - Recipient Domain',
        description: 'A DNS lookup against the recipient domain failed.',
        cause: 'Recipient domain has no MX record, MX records point to invalid or unreachable hosts, or DNS infrastructure is failing.',
        fix: 'Run nslookup or Resolve-DnsName -Type MX against the recipient domain. Check from the sending server\'s DNS resolver. If their MX is broken, contact the recipient organization.',
        severity: 'Error',
      },
      {
        code: '5.4.30',
        name: 'Organization MX Records Invalid',
        description: 'Your own organization\'s MX records are misconfigured and inbound mail cannot be routed correctly.',
        cause: 'MX records point to a host that no longer accepts mail, points to an internal address, or has TTL/propagation issues after a recent change.',
        fix: 'Verify your MX records publicly with mxtoolbox.com. For M365 the MX should point to <tenant>.mail.protection.outlook.com. After any change, allow up to 24 hours for global propagation.',
        severity: 'Critical',
      },
      {
        code: '5.4.450',
        name: 'Delivery Rejected by Mail Flow Rule',
        description: 'A mail flow (transport) rule rejected the message.',
        cause: 'An EOP or on-premises transport rule matched and the action was "reject the message". Common for DLP policies, attachment blocks, or content-based rejections.',
        fix: 'Review mail flow rules in Exchange Admin Center. Use Get-MessageTrace and Get-MessageTraceDetail to identify which rule matched. Adjust the rule or message content.',
        severity: 'Error',
      },
    ],
  },
  {
    category: 'TLS & Certificate Errors (5.7.3xx / 4.7.x)',
    codes: [
      {
        code: '5.7.3',
        name: 'STARTTLS Required',
        description: 'The destination server requires TLS but the connection failed.',
        cause: 'TLS certificate issue on the receiving end, or connector configured to require TLS.',
        fix: 'Check the certificate on the destination mail server. Review connector TLS settings.',
        severity: 'Error',
      },
      {
        code: '5.7.321',
        name: 'Certificate Validation Failed',
        description: 'The destination server TLS certificate failed validation.',
        cause: 'Expired, self-signed, or mismatched certificate on the receiving server. In hybrid environments, the on-premises Exchange certificate may not match what is configured in the EXO hybrid connector.',
        fix: 'Check the receiving server TLS certificate. If using a connector, you may need to disable certificate validation temporarily. For hybrid: ensure the on-premises Exchange certificate matches what is configured in the Exchange Online connector, and re-run the Hybrid Configuration Wizard if needed.',
        severity: 'Error',
      },
      {
        code: '5.7.322',
        name: 'Certificate Expired',
        description: 'The TLS certificate on the destination server has expired.',
        cause: 'The mail server certificate is past its expiration date.',
        fix: 'Renew the TLS certificate on the receiving mail server.',
        severity: 'Error',
      },
      {
        code: '5.7.323',
        name: 'TLS Required by Policy',
        description: 'The message was rejected because TLS is required by policy.',
        cause: 'A transport rule or connector requires TLS but the connection could not be established.',
        fix: 'Ensure both sides support TLS. Review connector TLS requirements.',
        severity: 'Error',
      },
      {
        code: '5.7.324',
        name: 'Certificate Does Not Match Domain',
        description: 'The TLS certificate does not match the destination domain.',
        cause: 'The CN or SAN on the certificate does not include the mail server hostname.',
        fix: 'Update the certificate to include the correct hostname, or adjust connector settings.',
        severity: 'Error',
      },
      {
        code: '5.7.325',
        name: 'Certificate Not Trusted',
        description: 'The TLS certificate is not trusted.',
        cause: 'The certificate is self-signed or the CA is not in the trust store.',
        fix: 'Use a certificate from a trusted public CA, or add the CA to the trust store.',
        severity: 'Error',
      },
      {
        code: '4.7.26',
        name: 'DMARC Policy Violation - Quarantine',
        description: 'Message quarantined due to DMARC policy.',
        cause: 'The message failed DMARC alignment and the policy is p=quarantine.',
        fix: 'Ensure SPF and DKIM are properly configured and aligned with the From domain.',
        severity: 'Warning',
      },
    ],
  },
  {
    category: 'Transient / Temporary Failures (4.x.x)',
    codes: [
      {
        code: '4.2.1',
        name: 'Mailbox Busy',
        description: 'The destination mailbox is temporarily busy.',
        cause: 'The mailbox is being accessed by another process or is temporarily locked.',
        fix: 'Retry delivery. Usually resolves automatically.',
        severity: 'Info',
      },
      {
        code: '4.2.2',
        name: 'Mailbox Full - Temporary',
        description: 'The mailbox is temporarily full.',
        cause: 'The recipient mailbox has exceeded its quota.',
        fix: 'Notify the recipient to free up space. Consider increasing quota.',
        severity: 'Warning',
      },
      {
        code: '4.3.1',
        name: 'Insufficient System Resources',
        description: 'The destination server is temporarily out of resources.',
        cause: 'Server disk space, memory, or queue is full.',
        fix: 'Usually self-resolving. If persistent, check destination server health.',
        severity: 'Warning',
      },
      {
        code: '4.3.2',
        name: 'Service Not Available',
        description: 'The destination mail service is temporarily unavailable.',
        cause: 'Server maintenance, overload, or temporary outage.',
        fix: 'Retry later. If persistent after 24 hours, investigate destination server availability.',
        severity: 'Warning',
      },
      {
        code: '4.6.5',
        name: 'Multi-Language Situation',
        description: 'A multi-language message could not be delivered temporarily.',
        cause: 'Language conversion error during delivery attempt.',
        fix: 'Retry delivery. If persistent, check message encoding settings.',
        severity: 'Info',
      },
      {
        code: '4.7.0',
        name: 'Certificate Expired - Temporary',
        description: 'TLS handshake failed temporarily due to certificate issue.',
        cause: 'Certificate validation failure during a transient TLS negotiation.',
        fix: 'Check TLS certificate validity. Will retry automatically.',
        severity: 'Warning',
      },
      {
        code: '4.7.1',
        name: 'Delivery Not Authorized - Temporary',
        description: 'The sending domain is temporarily not authorized to send.',
        cause: 'Temporary restriction on the sending domain, often due to reputation.',
        fix: 'Retry later. Check sending domain reputation if recurring.',
        severity: 'Warning',
      },
    ],
  },
  {
    category: 'Hybrid Exchange Errors',
    codes: [
      {
        code: '5.7.124',
        name: 'Not Authorized - Hybrid Connector',
        description: 'The sending server is not authorized to use the hybrid send connector.',
        cause: 'The on-premises server IP or certificate is not matched in the Exchange Online inbound connector.',
        fix: 'Update the inbound connector in Exchange Online to trust the on-premises server certificate or IP range.',
        severity: 'Error',
      },
      {
        code: '4.4.62',
        name: 'Mail Routing Issue - Hybrid',
        description: 'Mail routing issue, contact your administrator. Common during hybrid coexistence and migrations.',
        cause: 'Accepted domain misconfiguration, missing connector, or stale TargetAddress on a mail-enabled user/mailbox after a migration. The message has nowhere to go because routing logic loops or terminates.',
        fix: 'Verify accepted domain type (Authoritative vs Internal Relay) on both sides. Check the recipient TargetAddress / ExternalEmailAddress for stale routing pointers. Confirm hybrid send/receive connectors exist and are healthy.',
        severity: 'Error',
      },
      {
        code: '5.7.380',
        name: 'Hybrid Mail Flow Authentication Failed',
        description: 'A hybrid mail flow message failed authentication between on-premises and Exchange Online.',
        cause: 'Hybrid connector certificate mismatch, expired hybrid certificate, or organization relationship token issue.',
        fix: 'Verify the hybrid certificate is valid and matches on both ends. Re-run the Hybrid Configuration Wizard. Check the Organization Relationship and OAuth configuration with Test-OAuthConnectivity.',
        severity: 'Error',
      },
    ],
  },
];
