export const portCategories: {
  category: string
  ports: {
    port: number | string
    protocol: 'TCP' | 'UDP' | 'TCP/UDP'
    service: string
    description: string
    dangerous: boolean
    notes?: string
  }[]
}[] = [
  {
    category: 'Web & HTTP',
    ports: [
      { port: 80, protocol: 'TCP', service: 'HTTP', description: 'Unencrypted web traffic. Should be redirected to HTTPS in all modern deployments.', dangerous: false },
      { port: 443, protocol: 'TCP', service: 'HTTPS', description: 'Encrypted web traffic over TLS/SSL. Standard for all web services.', dangerous: false },
      { port: 8080, protocol: 'TCP', service: 'HTTP Alternate', description: 'Common alternate HTTP port used by web proxies, dev servers, and some admin interfaces.', dangerous: false },
      { port: 8443, protocol: 'TCP', service: 'HTTPS Alternate', description: 'Alternate HTTPS port commonly used by Tomcat, Proxmox, pfSense, and other web UIs.', dangerous: false },
      { port: 8888, protocol: 'TCP', service: 'HTTP Alternate', description: 'Common alternate web port used by Jupyter notebooks and various applications.', dangerous: false },
      { port: 3000, protocol: 'TCP', service: 'Dev HTTP / Grafana', description: 'Common development server port used by Node.js, React, and Grafana.', dangerous: false },
      { port: 9090, protocol: 'TCP', service: 'HTTP Alternate / Prometheus', description: 'Used by Prometheus, Cockpit, and various web admin interfaces.', dangerous: false },
      { port: 8008, protocol: 'TCP', service: 'HTTP Alternate', description: 'Alternate HTTP port used by Google Chromecast, Home Assistant, and some IoT devices.', dangerous: false },
      { port: 8081, protocol: 'TCP', service: 'HTTP Alternate', description: 'Alternate HTTP port used by many management interfaces and proxies.', dangerous: false },
      { port: 8123, protocol: 'TCP', service: 'Home Assistant', description: 'Home Assistant web interface default port.', dangerous: false },
      { port: 8888, protocol: 'TCP', service: 'Jupyter / HTTP Alt', description: 'Jupyter Notebook web interface and alternate HTTP.', dangerous: false },
      { port: 9443, protocol: 'TCP', service: 'HTTPS Alternate', description: 'Alternate HTTPS port used by some management interfaces.', dangerous: false },
    ],
  },
  {
    category: 'Email',
    ports: [
      { port: 25, protocol: 'TCP', service: 'SMTP', description: 'Simple Mail Transfer Protocol. Server-to-server email relay. Often blocked outbound by ISPs to prevent spam.', dangerous: true, notes: 'Commonly exploited for open relay and spam. Block outbound on end-user networks.' },
      { port: 465, protocol: 'TCP', service: 'SMTPS', description: 'SMTP over SSL. Legacy implicit TLS port for email submission. Deprecated in favor of 587 but still widely used.', dangerous: false },
      { port: 587, protocol: 'TCP', service: 'SMTP Submission', description: 'Modern email submission port. Requires authentication and STARTTLS. Use this for outbound email from clients and applications.', dangerous: false },
      { port: 110, protocol: 'TCP', service: 'POP3', description: 'Post Office Protocol v3. Downloads email from server. Unencrypted — use 995 instead.', dangerous: true, notes: 'Transmits credentials in plaintext. Disable in favor of IMAPS.' },
      { port: 995, protocol: 'TCP', service: 'POP3S', description: 'POP3 over SSL/TLS. Encrypted email retrieval.', dangerous: false },
      { port: 143, protocol: 'TCP', service: 'IMAP', description: 'Internet Message Access Protocol. Syncs email from server. Unencrypted — use 993 instead.', dangerous: true, notes: 'Transmits credentials in plaintext. Disable in favor of IMAPS.' },
      { port: 993, protocol: 'TCP', service: 'IMAPS', description: 'IMAP over SSL/TLS. Encrypted email sync. Standard for modern email clients.', dangerous: false },
    ],
  },
  {
    category: 'File Transfer',
    ports: [
      { port: 20, protocol: 'TCP', service: 'FTP Data', description: 'FTP data transfer channel (active mode). Unencrypted.', dangerous: true, notes: 'Transmits data and credentials in plaintext. Replace with SFTP (22) or FTPS (990).' },
      { port: 21, protocol: 'TCP', service: 'FTP Control', description: 'FTP command channel. Unencrypted.', dangerous: true, notes: 'Transmits credentials in plaintext. Replace with SFTP (22) or FTPS (990).' },
      { port: 22, protocol: 'TCP', service: 'SSH / SFTP / SCP', description: 'Secure Shell, Secure File Transfer Protocol, and Secure Copy. Encrypted remote access and file transfer.', dangerous: false, notes: 'Change to non-standard port and restrict to known IPs if internet-facing.' },
      { port: 69, protocol: 'UDP', service: 'TFTP', description: 'Trivial File Transfer Protocol. No authentication. Used for PXE boot and network device firmware updates.', dangerous: true, notes: 'No authentication or encryption. Restrict to management VLANs only.' },
      { port: 990, protocol: 'TCP', service: 'FTPS', description: 'FTP over implicit TLS. Encrypted FTP.', dangerous: false },
      { port: 989, protocol: 'TCP', service: 'FTPS Data', description: 'FTPS data channel over implicit TLS.', dangerous: false },
      { port: 2049, protocol: 'TCP/UDP', service: 'NFS', description: 'Network File System. Unix/Linux file sharing.', dangerous: true, notes: 'Restrict to trusted hosts. Use NFSv4 with Kerberos for authentication.' },
      { port: 445, protocol: 'TCP', service: 'SMB / CIFS', description: 'Server Message Block. Windows file sharing, AD replication, and remote management.', dangerous: true, notes: 'Never expose to internet. Enable SMB signing. Block SMBv1.' },
      { port: 139, protocol: 'TCP', service: 'NetBIOS Session / SMB', description: 'Legacy SMB over NetBIOS. Replaced by port 445.', dangerous: true, notes: 'Block externally. Disable NetBIOS over TCP/IP.' },
    ],
  },
  {
    category: 'Remote Access',
    ports: [
      { port: 22, protocol: 'TCP', service: 'SSH', description: 'Secure Shell. Encrypted remote terminal access. Standard for Linux/Unix administration.', dangerous: false, notes: 'Restrict to known IPs. Disable password auth and use key-based auth.' },
      { port: 23, protocol: 'TCP', service: 'Telnet', description: 'Unencrypted remote terminal. Transmits everything including credentials in plaintext.', dangerous: true, notes: 'Never use. Replace with SSH (22) in all environments.' },
      { port: 3389, protocol: 'TCP', service: 'RDP', description: 'Remote Desktop Protocol. Windows remote desktop access. High-value target for attackers.', dangerous: true, notes: 'Never expose directly to internet. Use VPN or RD Gateway. Enable NLA and restrict by IP.' },
      { port: 5900, protocol: 'TCP', service: 'VNC', description: 'Virtual Network Computing. Remote desktop for non-Windows systems. Unencrypted by default.', dangerous: true, notes: 'Tunnel through SSH or VPN. Never expose directly to internet.' },
      { port: 5985, protocol: 'TCP', service: 'WinRM HTTP', description: 'Windows Remote Management over HTTP. Used by PowerShell Remoting.', dangerous: true, notes: 'Unencrypted. Use WinRM HTTPS (5986) or restrict to management networks only.' },
      { port: 5986, protocol: 'TCP', service: 'WinRM HTTPS', description: 'Windows Remote Management over HTTPS. Encrypted PowerShell remoting.', dangerous: false },
      { port: 2222, protocol: 'TCP', service: 'SSH Alternate', description: 'Common alternate SSH port used to reduce automated scanning noise.', dangerous: false },
      { port: 4899, protocol: 'TCP', service: 'Radmin', description: 'Remote Administrator (Radmin) remote control software.', dangerous: true, notes: 'Restrict to management networks. Has been exploited in ransomware attacks.' },
      { port: 5631, protocol: 'TCP', service: 'pcAnywhere', description: 'Symantec pcAnywhere remote access. Legacy remote control software.', dangerous: true, notes: 'Legacy software with known vulnerabilities. Replace with modern alternatives.' },
      { port: 5632, protocol: 'UDP', service: 'pcAnywhere', description: 'pcAnywhere UDP status port.', dangerous: true, notes: 'Legacy software. Replace with modern alternatives.' },
    ],
  },
  {
    category: 'DNS & Network Services',
    ports: [
      { port: 53, protocol: 'TCP/UDP', service: 'DNS', description: 'Domain Name System. UDP for queries, TCP for zone transfers and large responses.', dangerous: false, notes: 'Restrict zone transfers (TCP 53) to authorized secondary DNS servers only.' },
      { port: 67, protocol: 'UDP', service: 'DHCP Server', description: 'Dynamic Host Configuration Protocol server. Assigns IP addresses to clients.', dangerous: false },
      { port: 68, protocol: 'UDP', service: 'DHCP Client', description: 'DHCP client port. Receives IP configuration from DHCP server.', dangerous: false },
      { port: 123, protocol: 'UDP', service: 'NTP', description: 'Network Time Protocol. Time synchronization. Critical for Kerberos and certificate validity.', dangerous: false, notes: 'Clock skew over 5 minutes breaks Kerberos authentication.' },
      { port: 161, protocol: 'UDP', service: 'SNMP', description: 'Simple Network Management Protocol. Network device monitoring and management.', dangerous: true, notes: 'Use SNMPv3 with authentication and encryption. SNMPv1/v2c use community strings (plaintext passwords).' },
      { port: 162, protocol: 'UDP', service: 'SNMP Trap', description: 'SNMP trap receiver. Devices send unsolicited notifications to management systems.', dangerous: false },
      { port: 5353, protocol: 'UDP', service: 'mDNS / Bonjour', description: 'Multicast DNS. Zero-configuration name resolution on local networks.', dangerous: true, notes: 'Can leak hostnames and service information. Disable on corporate networks or restrict to specific VLANs.' },
      { port: 5355, protocol: 'UDP', service: 'LLMNR', description: 'Link-Local Multicast Name Resolution. Windows name resolution fallback when DNS fails.', dangerous: true, notes: 'Disable via GPO. Commonly exploited by Responder for credential capture on internal networks.' },
      { port: 137, protocol: 'UDP', service: 'NetBIOS Name Service', description: 'NetBIOS name service. Legacy Windows name resolution.', dangerous: true, notes: 'Disable NetBIOS over TCP/IP. Exploited by Responder and other MITM tools.' },
      { port: 138, protocol: 'UDP', service: 'NetBIOS Datagram', description: 'NetBIOS datagram service. Used for Windows browsing and legacy SMB.', dangerous: true, notes: 'Disable with NetBIOS. Not needed in modern networks.' },
      { port: 853, protocol: 'TCP', service: 'DNS over TLS (DoT)', description: 'DNS over TLS. Encrypted DNS queries to prevent eavesdropping.', dangerous: false },
      { port: 784, protocol: 'UDP', service: 'DNS over QUIC', description: 'DNS over QUIC protocol. Encrypted DNS transport.', dangerous: false },
    ],
  },
  {
    category: 'Windows & Active Directory',
    ports: [
      { port: 88, protocol: 'TCP/UDP', service: 'Kerberos', description: 'Kerberos authentication. Core of Active Directory authentication.', dangerous: false },
      { port: 135, protocol: 'TCP', service: 'RPC Endpoint Mapper', description: 'Microsoft RPC endpoint mapper. Required for AD replication, WMI, and DCOM.', dangerous: true, notes: 'Restrict to management networks. Block from internet.' },
      { port: 389, protocol: 'TCP/UDP', service: 'LDAP', description: 'Lightweight Directory Access Protocol. Unencrypted AD queries and authentication.', dangerous: true, notes: 'Use LDAPS (636) for encrypted LDAP. Plain LDAP transmits credentials in cleartext.' },
      { port: 636, protocol: 'TCP', service: 'LDAPS', description: 'LDAP over SSL/TLS. Encrypted Active Directory queries.', dangerous: false },
      { port: 3268, protocol: 'TCP', service: 'Global Catalog LDAP', description: 'Active Directory Global Catalog LDAP. Used to query all objects across all domains in a forest.', dangerous: false },
      { port: 3269, protocol: 'TCP', service: 'Global Catalog LDAPS', description: 'Global Catalog LDAP over SSL. Encrypted cross-domain AD queries.', dangerous: false },
      { port: 464, protocol: 'TCP/UDP', service: 'Kerberos Password Change', description: 'Kerberos password change protocol (kpasswd). Used for AD password changes.', dangerous: false },
      { port: 593, protocol: 'TCP', service: 'RPC over HTTP', description: 'RPC over HTTP. Used by Outlook Anywhere and some Exchange services.', dangerous: false },
      { port: 9389, protocol: 'TCP', service: 'AD Web Services', description: 'Active Directory Web Services. Used by Active Directory Administrative Center and PowerShell AD module.', dangerous: false },
      { port: 49152, protocol: 'TCP', service: 'RPC Dynamic Range Start', description: 'Start of Windows RPC dynamic port range (49152-65535). AD replication, WMI, DCOM negotiate ports in this range.', dangerous: false },
    ],
  },
  {
    category: 'Database',
    ports: [
      { port: 1433, protocol: 'TCP', service: 'MS SQL Server', description: 'Microsoft SQL Server. Never expose directly to internet.', dangerous: true, notes: 'Restrict to application servers only. Use Windows auth over SQL auth where possible.' },
      { port: 1434, protocol: 'UDP', service: 'MS SQL Browser', description: 'SQL Server Browser service. Returns SQL instance information to clients.', dangerous: true, notes: 'Disable if using fixed port. Leaks SQL instance names and versions.' },
      { port: 3306, protocol: 'TCP', service: 'MySQL / MariaDB', description: 'MySQL and MariaDB database server.', dangerous: true, notes: 'Restrict to localhost or application server. Never expose to internet.' },
      { port: 5432, protocol: 'TCP', service: 'PostgreSQL', description: 'PostgreSQL database server.', dangerous: true, notes: 'Restrict to localhost or application server. Never expose to internet.' },
      { port: 1521, protocol: 'TCP', service: 'Oracle DB', description: 'Oracle Database listener.', dangerous: true, notes: 'Restrict to application servers only.' },
      { port: 27017, protocol: 'TCP', service: 'MongoDB', description: 'MongoDB database server. No authentication by default in older versions.', dangerous: true, notes: 'Bind to localhost only. Enable authentication. Many breaches from internet-exposed MongoDB.' },
      { port: 6379, protocol: 'TCP', service: 'Redis', description: 'Redis in-memory data store. No authentication by default.', dangerous: true, notes: 'Bind to localhost or use requirepass. Internet-exposed Redis is a common breach vector.' },
      { port: 5984, protocol: 'TCP', service: 'CouchDB', description: 'Apache CouchDB HTTP API.', dangerous: true, notes: 'Restrict to localhost. Default admin party mode (no auth) in older versions.' },
      { port: 9042, protocol: 'TCP', service: 'Cassandra', description: 'Apache Cassandra CQL native transport port.', dangerous: true, notes: 'Restrict to cluster nodes and application servers.' },
      { port: 7474, protocol: 'TCP', service: 'Neo4j HTTP', description: 'Neo4j graph database HTTP API.', dangerous: true, notes: 'Restrict access. Default credentials have been commonly left unchanged.' },
    ],
  },
  {
    category: 'VPN & Tunneling',
    ports: [
      { port: 1194, protocol: 'UDP', service: 'OpenVPN', description: 'OpenVPN default port. SSL/TLS-based VPN.', dangerous: false },
      { port: 1723, protocol: 'TCP', service: 'PPTP', description: 'Point-to-Point Tunneling Protocol. Legacy VPN protocol with known cryptographic weaknesses.', dangerous: true, notes: 'Deprecated. MS-CHAPv2 is broken. Use IKEv2, OpenVPN, or WireGuard instead.' },
      { port: 500, protocol: 'UDP', service: 'IKE / IPSec', description: 'Internet Key Exchange. Used for IPSec VPN tunnel establishment.', dangerous: false },
      { port: 4500, protocol: 'UDP', service: 'IPSec NAT-T', description: 'IPSec NAT Traversal. Allows IPSec through NAT devices.', dangerous: false },
      { port: 1701, protocol: 'UDP', service: 'L2TP', description: 'Layer 2 Tunneling Protocol. Used with IPSec for L2TP/IPSec VPN.', dangerous: false },
      { port: 51820, protocol: 'UDP', service: 'WireGuard', description: 'WireGuard VPN. Modern, fast, and cryptographically sound VPN protocol.', dangerous: false },
      { port: 10000, protocol: 'TCP', service: 'Webmin / VPN Alt', description: 'Webmin web admin interface and some VPN products.', dangerous: true, notes: 'Restrict Webmin to management networks.' },
      { port: 1080, protocol: 'TCP', service: 'SOCKS Proxy', description: 'SOCKS proxy protocol. Used by many applications for proxied connections.', dangerous: true, notes: 'Open SOCKS proxies are commonly abused for anonymization and traffic routing.' },
    ],
  },
  {
    category: 'VoIP & Unified Communications',
    ports: [
      { port: 5060, protocol: 'TCP/UDP', service: 'SIP', description: 'Session Initiation Protocol. VoIP call signaling. Unencrypted.', dangerous: true, notes: 'Commonly scanned and attacked. Use SIPS (5061) or restrict to SBC/carrier IP ranges.' },
      { port: 5061, protocol: 'TCP', service: 'SIPS', description: 'SIP over TLS. Encrypted VoIP signaling.', dangerous: false },
      { port: '10000-20000', protocol: 'UDP', service: 'RTP Media', description: 'Real-time Transport Protocol. Carries actual audio/video streams for VoIP.', dangerous: false },
      { port: '16384-32767', protocol: 'UDP', service: 'RTP Media (Cisco)', description: 'Cisco RTP media port range for VoIP audio streams.', dangerous: false },
      { port: 1720, protocol: 'TCP', service: 'H.323', description: 'H.323 VoIP call signaling. Legacy video conferencing and VoIP standard.', dangerous: false },
      { port: 3478, protocol: 'TCP/UDP', service: 'STUN / Teams Media', description: 'STUN protocol for NAT traversal. Also used by Microsoft Teams for media.', dangerous: false },
      { port: 3479, protocol: 'TCP/UDP', service: 'Teams Media', description: 'Microsoft Teams media transport port.', dangerous: false },
      { port: 3480, protocol: 'TCP/UDP', service: 'Teams Media', description: 'Microsoft Teams media transport port.', dangerous: false },
      { port: 3481, protocol: 'TCP/UDP', service: 'Teams Media', description: 'Microsoft Teams media transport port.', dangerous: false },
      { port: 19302, protocol: 'UDP', service: 'Google STUN', description: 'Google STUN server for WebRTC NAT traversal (stun.l.google.com).', dangerous: false },
      { port: 5349, protocol: 'TCP', service: 'STUN/TURN over TLS', description: 'STUN and TURN over TLS for WebRTC and VoIP NAT traversal.', dangerous: false },
      { port: 8801, protocol: 'TCP/UDP', service: 'Zoom', description: 'Zoom video conferencing fallback port.', dangerous: false },
      { port: 8802, protocol: 'TCP/UDP', service: 'Zoom', description: 'Zoom video conferencing alternate port.', dangerous: false },
    ],
  },
  {
    category: 'RMM & MSP Tools',
    ports: [
      { port: 5721, protocol: 'TCP', service: 'Kaseya VSA Agent', description: 'Kaseya VSA agent communication port. Used by Kaseya RMM agents to communicate with VSA server.', dangerous: false, notes: 'Restrict to Kaseya VSA server IP. Exploited in 2021 ransomware attack (CVE-2021-30116).' },
      { port: 443, protocol: 'TCP', service: 'Kaseya / ConnectWise HTTPS', description: 'Most modern RMM tools communicate over HTTPS/443 to cloud endpoints.', dangerous: false },
      { port: 8041, protocol: 'TCP', service: 'ConnectWise Automate', description: 'ConnectWise Automate (LabTech) agent communication port.', dangerous: false },
      { port: 80, protocol: 'TCP', service: 'ConnectWise Automate HTTP', description: 'ConnectWise Automate agent fallback HTTP port.', dangerous: false },
      { port: 65000, protocol: 'TCP', service: 'Datto RMM', description: 'Datto RMM agent communication port.', dangerous: false },
      { port: 8200, protocol: 'TCP', service: 'Datto RMM Alt', description: 'Datto RMM alternate agent port.', dangerous: false },
      { port: 4343, protocol: 'TCP', service: 'N-able N-central', description: 'N-able N-central agent communication port.', dangerous: false },
      { port: 10001, protocol: 'TCP', service: 'NinjaRMM', description: 'NinjaRMM agent communication port.', dangerous: false },
      { port: 6543, protocol: 'TCP', service: 'Atera', description: 'Atera RMM agent communication port.', dangerous: false },
      { port: 5000, protocol: 'TCP', service: 'Syncro RMM', description: 'Syncro RMM platform communication port.', dangerous: false },
    ],
  },
  {
    category: 'Backup & Recovery',
    ports: [
      { port: 9392, protocol: 'TCP', service: 'Veeam Backup', description: 'Veeam Backup & Replication server default management port.', dangerous: false },
      { port: 9401, protocol: 'TCP', service: 'Veeam Catalog', description: 'Veeam catalog service port.', dangerous: false },
      { port: '2500-5000', protocol: 'TCP', service: 'Veeam Data Transfer', description: 'Veeam data transfer port range between backup infrastructure components.', dangerous: false },
      { port: 10002, protocol: 'TCP', service: 'Veeam Mount Service', description: 'Veeam mount service for instant VM recovery.', dangerous: false },
      { port: 9876, protocol: 'TCP', service: 'Acronis Agent', description: 'Acronis Cyber Protect / Backup agent communication port.', dangerous: false },
      { port: 44445, protocol: 'TCP', service: 'Acronis Management', description: 'Acronis management server communication port.', dangerous: false },
      { port: 55000, protocol: 'TCP', service: 'Datto BCDR', description: 'Datto BCDR (backup/continuity) device communication port.', dangerous: false },
      { port: 8882, protocol: 'TCP', service: 'Datto Agent', description: 'Datto backup agent port.', dangerous: false },
      { port: 6783, protocol: 'TCP', service: 'Zerto', description: 'Zerto replication engine port.', dangerous: false },
      { port: 4009, protocol: 'TCP', service: 'Commvault', description: 'Commvault data protection communication port.', dangerous: false },
      { port: 8400, protocol: 'TCP', service: 'Commvault Services', description: 'Commvault CommServe and MediaAgent communication.', dangerous: false },
    ],
  },
  {
    category: 'Security & Authentication',
    ports: [
      { port: 1812, protocol: 'UDP', service: 'RADIUS Auth', description: 'RADIUS authentication. Used for 802.1X, VPN, and Wi-Fi authentication.', dangerous: false },
      { port: 1813, protocol: 'UDP', service: 'RADIUS Accounting', description: 'RADIUS accounting. Logs authentication events.', dangerous: false },
      { port: 1645, protocol: 'UDP', service: 'RADIUS Auth (legacy)', description: 'Legacy RADIUS authentication port. Deprecated in favor of 1812.', dangerous: false },
      { port: 49, protocol: 'TCP', service: 'TACACS+', description: 'Terminal Access Controller Access-Control System. Used for network device authentication.', dangerous: false },
      { port: 443, protocol: 'TCP', service: 'SAML / OAuth / OIDC', description: 'Modern identity protocols (SAML, OAuth 2.0, OpenID Connect) run over HTTPS/443.', dangerous: false },
      { port: 8834, protocol: 'TCP', service: 'Nessus', description: 'Nessus vulnerability scanner web interface.', dangerous: false },
      { port: 9390, protocol: 'TCP', service: 'OpenVAS / GVM', description: 'OpenVAS/Greenbone Vulnerability Manager service port.', dangerous: false },
      { port: 4444, protocol: 'TCP', service: 'Metasploit / Common Attack', description: 'Default Metasploit listener port. Also used by some malware for C2.', dangerous: true, notes: 'Block inbound/outbound. Commonly used by Metasploit and various malware for reverse shells.' },
      { port: 31337, protocol: 'TCP', service: 'Back Orifice / Elite', description: 'Back Orifice legacy RAT port. Used by old-school malware.', dangerous: true, notes: 'Block. Any traffic on this port is suspicious.' },
    ],
  },
  {
    category: 'Monitoring & Management',
    ports: [
      { port: 514, protocol: 'UDP', service: 'Syslog', description: 'Syslog protocol. Unencrypted log forwarding to SIEM or syslog server.', dangerous: false, notes: 'Use syslog over TLS (6514) for sensitive log data.' },
      { port: 6514, protocol: 'TCP', service: 'Syslog TLS', description: 'Syslog over TLS. Encrypted log forwarding.', dangerous: false },
      { port: 9100, protocol: 'TCP', service: 'Prometheus Node Exporter', description: 'Prometheus Node Exporter metrics endpoint. Exposes system metrics.', dangerous: false },
      { port: 9200, protocol: 'TCP', service: 'Elasticsearch HTTP', description: 'Elasticsearch REST API. No authentication in older versions.', dangerous: true, notes: 'Restrict to localhost or monitoring network. Many breaches from internet-exposed Elasticsearch.' },
      { port: 9300, protocol: 'TCP', service: 'Elasticsearch Transport', description: 'Elasticsearch node-to-node transport protocol.', dangerous: true, notes: 'Restrict to Elasticsearch cluster nodes only.' },
      { port: 5601, protocol: 'TCP', service: 'Kibana', description: 'Kibana web UI for Elasticsearch. Restrict to management network.', dangerous: false },
      { port: 8086, protocol: 'TCP', service: 'InfluxDB', description: 'InfluxDB time series database HTTP API.', dangerous: false },
      { port: 8291, protocol: 'TCP', service: 'Winbox (MikroTik)', description: 'MikroTik Winbox management protocol.', dangerous: true, notes: 'Restrict to management VLAN. CVE-2018-14847 exploited this port.' },
      { port: 8728, protocol: 'TCP', service: 'MikroTik API', description: 'MikroTik RouterOS API. Unencrypted.', dangerous: true, notes: 'Use API-SSL (8729) instead. Restrict to management VLAN.' },
      { port: 8729, protocol: 'TCP', service: 'MikroTik API-SSL', description: 'MikroTik RouterOS API over SSL.', dangerous: false },
      { port: 8443, protocol: 'TCP', service: 'Unifi Controller', description: 'Ubiquiti UniFi Network Controller HTTPS management port.', dangerous: false },
      { port: 8080, protocol: 'TCP', service: 'Unifi HTTP Redirect', description: 'UniFi Controller HTTP redirect port.', dangerous: false },
      { port: 3478, protocol: 'UDP', service: 'UniFi STUN', description: 'UniFi STUN port for device communication.', dangerous: false },
      { port: 10001, protocol: 'UDP', service: 'UniFi Device Discovery', description: 'UniFi device discovery protocol (AP discovery).', dangerous: false },
      { port: 8880, protocol: 'TCP', service: 'UniFi HTTP Portal', description: 'UniFi guest portal HTTP port.', dangerous: false },
      { port: 8843, protocol: 'TCP', service: 'UniFi HTTPS Portal', description: 'UniFi guest portal HTTPS port.', dangerous: false },
      { port: 6789, protocol: 'TCP', service: 'UniFi Throughput Test', description: 'UniFi mobile speed test port.', dangerous: false },
    ],
  },
  {
    category: 'Infrastructure & Virtualization',
    ports: [
      { port: 443, protocol: 'TCP', service: 'vCenter / ESXi HTTPS', description: 'VMware vCenter and ESXi web management interface.', dangerous: false },
      { port: 902, protocol: 'TCP', service: 'VMware Remote Console', description: 'VMware remote console and VM heartbeat.', dangerous: false },
      { port: 903, protocol: 'TCP', service: 'VMware Remote Console Alt', description: 'VMware Remote Console alternate port.', dangerous: false },
      { port: 8006, protocol: 'TCP', service: 'Proxmox Web UI', description: 'Proxmox VE web management interface over HTTPS.', dangerous: false },
      { port: 3128, protocol: 'TCP', service: 'Squid Proxy / HTTP Proxy', description: 'Common HTTP proxy port used by Squid and other proxies.', dangerous: false },
      { port: 111, protocol: 'TCP/UDP', service: 'RPC Portmapper', description: 'RPC portmapper/rpcbind. Required for NFS and other RPC services.', dangerous: true, notes: 'Restrict to hosts requiring NFS. Block from internet.' },
      { port: 2375, protocol: 'TCP', service: 'Docker HTTP API', description: 'Docker daemon unencrypted API. Exposed Docker API gives root access to the host.', dangerous: true, notes: 'Never expose. Use Docker socket or TLS-secured API (2376) instead.' },
      { port: 2376, protocol: 'TCP', service: 'Docker HTTPS API', description: 'Docker daemon TLS-secured API.', dangerous: false },
      { port: 2377, protocol: 'TCP', service: 'Docker Swarm', description: 'Docker Swarm cluster management port.', dangerous: false },
      { port: 6443, protocol: 'TCP', service: 'Kubernetes API', description: 'Kubernetes API server. Restrict to management systems and CI/CD.', dangerous: false },
      { port: 10250, protocol: 'TCP', service: 'Kubernetes Kubelet', description: 'Kubernetes Kubelet API. Restrict to control plane nodes only.', dangerous: true, notes: 'Exposed Kubelet allows exec into containers. Restrict tightly.' },
      { port: 10255, protocol: 'TCP', service: 'Kubernetes Read-Only Kubelet', description: 'Kubernetes read-only Kubelet port. Disabled by default in newer versions.', dangerous: true, notes: 'Disable. Exposes pod and node information without authentication.' },
      { port: 2379, protocol: 'TCP', service: 'etcd Client', description: 'etcd distributed key-value store client port. Used by Kubernetes.', dangerous: true, notes: 'Restrict to control plane nodes. etcd contains all Kubernetes secrets.' },
      { port: 2380, protocol: 'TCP', service: 'etcd Peer', description: 'etcd peer communication port.', dangerous: true, notes: 'Restrict to etcd cluster members only.' },
    ],
  },
  {
    category: 'Printing & Discovery',
    ports: [
      { port: 9100, protocol: 'TCP', service: 'RAW Printing / JetDirect', description: 'Direct IP printing (RAW/JetDirect). Common for network printers.', dangerous: false },
      { port: 515, protocol: 'TCP', service: 'LPD / LPR', description: 'Line Printer Daemon. Legacy Unix printing protocol.', dangerous: false },
      { port: 631, protocol: 'TCP', service: 'IPP / CUPS', description: 'Internet Printing Protocol. Used by CUPS on Linux/Mac and Windows print services.', dangerous: false },
      { port: 1900, protocol: 'UDP', service: 'UPnP SSDP', description: 'Universal Plug and Play Simple Service Discovery Protocol.', dangerous: true, notes: 'Disable UPnP on routers and firewalls. Widely exploited for amplification attacks and internal network exposure.' },
      { port: 5357, protocol: 'TCP', service: 'WSDAPI / WSD', description: 'Web Services for Devices. Windows network discovery.', dangerous: false },
      { port: 3702, protocol: 'UDP', service: 'WS-Discovery', description: 'Web Services Dynamic Discovery. Used by network printers and cameras.', dangerous: false },
    ],
  },
  {
    category: 'Network Routing & Switching',
    ports: [
      { port: 179, protocol: 'TCP', service: 'BGP', description: 'Border Gateway Protocol. Internet routing protocol between autonomous systems.', dangerous: false },
      { port: 520, protocol: 'UDP', service: 'RIP', description: 'Routing Information Protocol. Legacy distance-vector routing protocol.', dangerous: false },
      { port: 521, protocol: 'UDP', service: 'RIPng', description: 'RIP next generation for IPv6.', dangerous: false },
      { port: 646, protocol: 'TCP/UDP', service: 'LDP', description: 'Label Distribution Protocol. Used in MPLS networks.', dangerous: false },
      { port: 1985, protocol: 'UDP', service: 'HSRP', description: 'Hot Standby Router Protocol. Cisco first-hop redundancy protocol.', dangerous: false },
      { port: 2000, protocol: 'TCP', service: 'Cisco SCCP', description: 'Cisco Skinny Client Control Protocol. Used by Cisco IP phones.', dangerous: false },
      { port: 4789, protocol: 'UDP', service: 'VXLAN', description: 'Virtual Extensible LAN. Network virtualization overlay protocol.', dangerous: false },
      { port: 8472, protocol: 'UDP', service: 'VXLAN (Linux)', description: 'VXLAN port used by Linux kernel and Flannel for container networking.', dangerous: false },
    ],
  },
  {
    category: 'Microsoft 365 & Exchange',
    ports: [
      { port: 25, protocol: 'TCP', service: 'SMTP (Exchange)', description: 'SMTP for server-to-server mail relay into Exchange Online.', dangerous: false },
      { port: 587, protocol: 'TCP', service: 'SMTP Submission', description: 'Authenticated SMTP submission for Exchange Online and hybrid connectors.', dangerous: false },
      { port: 443, protocol: 'TCP', service: 'Exchange Online / M365', description: 'All M365 services including Exchange Online, SharePoint, Teams, and Azure AD use HTTPS/443.', dangerous: false },
      { port: 993, protocol: 'TCP', service: 'IMAPS (Exchange)', description: 'Encrypted IMAP for Exchange Online and on-premises Exchange.', dangerous: false },
      { port: 995, protocol: 'TCP', service: 'POP3S (Exchange)', description: 'Encrypted POP3 for Exchange Online.', dangerous: false },
      { port: 80, protocol: 'TCP', service: 'Exchange AutoDiscover', description: 'Exchange AutoDiscover HTTP redirect. Redirects to HTTPS.', dangerous: false },
      { port: 443, protocol: 'TCP', service: 'Exchange AutoDiscover HTTPS', description: 'Exchange AutoDiscover and EWS (Exchange Web Services) over HTTPS.', dangerous: false },
    ],
  },
  {
    category: 'Industrial & IoT',
    ports: [
      { port: 502, protocol: 'TCP', service: 'Modbus', description: 'Modbus TCP. Industrial control system protocol. No authentication.', dangerous: true, notes: 'Restrict to industrial network segment. No authentication or encryption. Never expose to internet.' },
      { port: 47808, protocol: 'UDP', service: 'BACnet', description: 'Building Automation and Control network protocol. HVAC and building management systems.', dangerous: true, notes: 'Restrict to building management VLAN. No authentication in base protocol.' },
      { port: 4840, protocol: 'TCP', service: 'OPC-UA', description: 'OPC Unified Architecture. Modern industrial automation protocol with security features.', dangerous: false },
      { port: 102, protocol: 'TCP', service: 'S7 / Siemens PLC', description: 'Siemens S7 PLC communication protocol. Used by Siemens SCADA systems.', dangerous: true, notes: 'Never expose. Target of Stuxnet and other ICS attacks.' },
      { port: 1883, protocol: 'TCP', service: 'MQTT', description: 'Message Queuing Telemetry Transport. IoT messaging protocol. Unencrypted.', dangerous: true, notes: 'Use MQTTS (8883) for encrypted MQTT. Unauthenticated MQTT brokers are common.' },
      { port: 8883, protocol: 'TCP', service: 'MQTTS', description: 'MQTT over SSL/TLS. Encrypted IoT messaging.', dangerous: false },
      { port: 5683, protocol: 'UDP', service: 'CoAP', description: 'Constrained Application Protocol. Lightweight IoT protocol similar to HTTP.', dangerous: false },
      { port: 8554, protocol: 'TCP', service: 'RTSP', description: 'Real Time Streaming Protocol. IP camera video streams.', dangerous: true, notes: 'Restrict to security management systems. IP cameras are commonly attacked.' },
      { port: 554, protocol: 'TCP', service: 'RTSP', description: 'Real Time Streaming Protocol default port. IP camera and media streaming.', dangerous: true, notes: 'Restrict to security management systems. Never expose to internet.' },
    ],
  },
  {
    category: 'Commonly Attacked / Malware Ports',
    ports: [
      { port: 4444, protocol: 'TCP', service: 'Metasploit Default', description: 'Default Metasploit reverse shell listener. Used by many exploits and malware for C2.', dangerous: true, notes: 'Block inbound/outbound. Traffic on this port is almost always malicious in production environments.' },
      { port: 6666, protocol: 'TCP', service: 'IRC / Malware C2', description: 'IRC port. Legacy chat protocol commonly used by botnets for C2 communication.', dangerous: true, notes: 'Block outbound. IRC-based botnets are still active.' },
      { port: 6667, protocol: 'TCP', service: 'IRC / Malware C2', description: 'Standard IRC port. Commonly used by botnets for C2.', dangerous: true, notes: 'Block outbound. Unexpected IRC traffic indicates likely malware.' },
      { port: 6881, protocol: 'TCP/UDP', service: 'BitTorrent', description: 'BitTorrent P2P file sharing default port.', dangerous: true, notes: 'Block on corporate networks. Bandwidth consumption and potential copyright/malware risk.' },
      { port: 31337, protocol: 'TCP', service: 'Back Orifice', description: 'Back Orifice legacy Remote Access Trojan port.', dangerous: true, notes: 'Block. Any traffic here is suspicious.' },
      { port: 1337, protocol: 'TCP', service: 'Common Malware / Alt Services', description: 'Commonly used by malware and hackers as an alternate service port.', dangerous: true, notes: 'Unexpected traffic on this port warrants investigation.' },
      { port: 12345, protocol: 'TCP', service: 'NetBus RAT', description: 'NetBus Remote Access Trojan legacy port.', dangerous: true, notes: 'Block. Legacy RAT but still used in some malware.' },
      { port: 9001, protocol: 'TCP', service: 'Tor / Various', description: 'Tor network relay port. Also used by various legitimate services.', dangerous: true, notes: 'Investigate outbound connections. May indicate Tor usage for exfiltration.' },
      { port: 9030, protocol: 'TCP', service: 'Tor Directory', description: 'Tor directory service port.', dangerous: true, notes: 'Block outbound on corporate networks.' },
    ],
  },
];
